### ISSUE TITLE
Facing issues with chromedriver and geckodriver, Message: session not created: No matching capabilities found

### ISSUE THREAD

**Issue by anarang** [SergeyPirogov/webdriver_manager#142]
Hi,
I have been using webdriver_manager for a while now, it worked flawlessly with the following code snippets for both browsers until today. Suddenly, both the browsers have started giving the same error as:
```
raise exception_class(message, screen, stacktrace)                                                                                             |         |
|       | selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found  
```
Code snippets used for each browser:
```
options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--proxy-server=%s' % proxy_url)
options.add_argument('--proxy-auto-detect')
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), options=options)
OR
driver = webdriver.Chrome(ChromeDriverManager().install(), chrome_options=options)
```

browser versions:
$ google-chrome --version
Google Chrome 83.0.4103.106 

 $ firefox --version
Mozilla Firefox 78.0.2

I am looking for a resolution to get past this error and continue using webdriver_manager, please let me know. Looking forward to your reply.

**Comment by anarang** [comment]
@SergeyPirogov Any luck? The issue has been persistent on container as well.. I am getting the same errors while using Chrome and Firefox both.
Sharing the logs below:
```
[WDM] - Current google-chrome version is 84.0.4147
2020-08-03 12:36:49,272 - Current google-chrome version is 84.0.4147
[WDM] - Get LATEST driver version for 84.0.4147
2020-08-03 12:36:49,273 - Get LATEST driver version for 84.0.4147
[WDM] - There is no [linux64] chromedriver for browser 84.0.4147 in cache
2020-08-03 12:36:49,418 - There is no [linux64] chromedriver for browser 84.0.4147 in cache
[WDM] - Get LATEST driver version for 84.0.4147
2020-08-03 12:36:49,418 - Get LATEST driver version for 84.0.4147
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
2020-08-03 12:36:49,533 - Trying to download new driver from http://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/path/to/project/drivers/chromedriver/linux64/84.0.4147.30]
2020-08-03 12:36:50,299 - Driver has been saved in cache [/path/to/project/drivers/chromedriver/linux64/84.0.4147.30]
.
.
.
Caught unexpected exception while running test: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/lemoncheesecake/runner.py", line 51, in run_setup_funcs
    setup_func()
  File "/usr/local/lib/python3.7/site-packages/lemoncheesecake/fixture.py", line 168, in <lambda>
    lambda name: (lambda: self._setup_fixture(name), lambda: self._teardown_fixture(name)),
  File "/usr/local/lib/python3.7/site-packages/lemoncheesecake/fixture.py", line 159, in _setup_fixture
    self._results[name] = self._fixtures[name].execute(self._get_fixture_params(name))
  File "/usr/local/lib/python3.7/site-packages/lemoncheesecake/fixture.py", line 112, in execute
    return _FixtureResult(self.name, self.func(**params))
  File "/usr/local/lib/python3.7/site-packages/lemoncheesecake/fixture.py", line 68, in __init__
    self._result = next(result)
  File "/exec-tests/cheesecake-ui-tests/fixtures/fixture.py", line 141, in setup
    chrome_options=options)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found
```

**Comment by wblondel** [comment]
On your first message, I see:

```
$ google-chrome --version
Google Chrome 83.0.4103.106
```

and on your second message:
```
[WDM] - Current google-chrome version is 84.0.4147
2020-08-03 12:36:49,272 - Current google-chrome version is 84.0.4147
```

Do you have multiple versions of google chrome?

**Comment by anarang** [comment]
I don't have multiple versions of chrome or firefox, the first set of logs was from my local system and the second set of logs was from docker container. I updated to **fedora 32**  and the issue is persistent on both firefox and chrome versions:
```
$ google-chrome --version
Google Chrome 84.0.4147.105 

 $ firefox --version
Mozilla Firefox 79.0
```
It is downloading the webdrivers but still giving me this error: 
The below logs are from my local machine using fedora 32.

```
Caught unexpected exception while running test: Traceback (most recent call last):                                                   |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/lemoncheesecake/runner.py", line 51, in run_setup_funcs                     |         |
|       |     setup_func()                                                                                                                     |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/lemoncheesecake/fixture.py", line 168, in <lambda>                          |         |
|       |     lambda name: (lambda: self._setup_fixture(name), lambda: self._teardown_fixture(name)),                                          |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/lemoncheesecake/fixture.py", line 159, in _setup_fixture                    |         |
|       |     self._results[name] = self._fixtures[name].execute(self._get_fixture_params(name))                                               |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/lemoncheesecake/fixture.py", line 112, in execute                           |         |
|       |     return _FixtureResult(self.name, self.func(**params))                                                                            |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/lemoncheesecake/fixture.py", line 68, in __init__                           |         |
|       |     self._result = next(result)                                                                                                      |         |
|       |   File "/home/anarang/work/ccs/cheesecake-ui-tests/fixtures/fixture.py", line 151, in setup                                          |         |
|       |     driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), options=options)                                      |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__             |         |
|       |     RemoteWebDriver.__init__(                                                                                                        |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__              |         |
|       |     self.start_session(capabilities, browser_profile)                                                                                |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session         |         |
|       |     response = self.execute(Command.NEW_SESSION, parameters)                                                                         |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute               |         |
|       |     self.error_handler.check_response(response)                                                                                      |         |
|       |   File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response     |         |
|       |     raise exception_class(message, screen, stacktrace)                                                                               |         |
|       | selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities         
```
This issue has been persistent for the past 4 days and started appearing without any change, it's weird but annoying. I am looking for some help if possible. Thanks.

**Comment by SergeyPirogov** [comment]
@anarang it's not a problem of webdriver_manager. Try to set a version of required driver explicitly and see what will happen

**Comment by anarang** [comment]
@SergeyPirogov thank you for a response but what do you think can the problem be in this case since it started happening 4 days back and everything was working very well before that. how can I set the version using the webdriver_manager?

**Comment by SergeyPirogov** [comment]
```
driver = webdriver.Chrome(ChromeDriverManager(version='2.26').install())
```

**Comment by anarang** [comment]
It isn't working for me, I tried with the current chrome driver version to be used:
```
driver = webdriver.Chrome(ChromeDriverManager(version='84.0.4147.30').install(), chrome_options=options)
```
```
$ google-chrome --version
Google Chrome 84.0.4147.105 
```
Any reasons for the error that might help me debug and fix this.

**Comment by SergeyPirogov** [comment]
Please find chrome driver version on official website. Chrome version is not always the same as a driver version

**Comment by wblondel** [comment]
Could you provide with the output of `uname -a` and `lsb_release -a` ?
Also, what version of Selenium are you using? The latest?
Thank you

**Comment by anarang** [comment]
@wblondel yes, please find the details below:
```
>>> selenium.__version__
'3.141.0'

$ uname -a
Linux localhost.localdomain 5.7.11-200.fc32.x86_64 #1 SMP Wed Jul 29 17:15:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo
```
the webdriver_manager is still throwing the same error for me though.

**Comment by wblondel** [comment]
Thank you. I'll setup the same environment and try to reproduce your issue.

However I would like to point out that the error is thrown by Selenium, not by webdriver_manager. Could you try giving the webdriver path manually (without using the manager) to see if you get the same error?

**Comment by wblondel** [comment]
It's me again.

I took some more time trying to reproduce the issue. Long story short, I think the issue is in your IMPORTS. Details at the end.

I installed Fedora 32, with the latest Google Chrome version, Python 3 and Selenium.

 ```
[wblondel@localhost]$ uname -a
Linux localhost.localdomain 5.7.11-200.fc32.x86_64 #1 SMP Wed Jul 29 17:15:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

[wblondel@localhost]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 32 (Thirty Two)
Release:	32
Codename:	ThirtyTwo

[wblondel@localhost]$ python --version
Python 3.8.5

[wblondel@localhost]$ google-chrome --version
Google Chrome 84.0.4147.105
```

```
>>> selenium.__version__
'3.141.0'
```

I couldn't reproduce the issue, neither by using webdriver_manager nor by manually download ChromeDriver from https://chromedriver.chromium.org/ and using it.

Source code:
```python
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

proxy_url = '127.0.0.1'

options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--proxy-server=%s' % proxy_url)
options.add_argument('--proxy-auto-detect')

#driver = webdriver.Chrome(ChromeDriverManager().install(), options=options)
driver = webdriver.Chrome('./chromedriver', options=options)
```

The ChromeDriver version is:
```
[wblondel@localhost 142]$ ./chromedriver --version
ChromeDriver 84.0.4147.30 (48b3e868b4cc0aa7e8149519690b6f6949e110a8-refs/branch-heads/4147@{#310})
```

I tested **the exact same code** on Windows, with the same version of everything (Python, Selenium, Google Chrome, and ChromeDriver, and no issue neither.

### **HOWEVER**

and I think that's where your mistake is,

if I mistakenly import 
```
from selenium.webdriver.firefox.options import Options
```
instead of
```
from selenium.webdriver.chrome.options import Options
```

and use it with Chrome, I will have the same error as you:

Traceback:
```
[wblondel@localhost 142]$ python main.py 
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    driver = webdriver.Chrome('./chromedriver', options=options)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/wblondel/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: No matching capabilities found
```

**Comment by anarang** [comment]
Hi @wblondel thank you for looking into it. It resolved the issue for chrome and is working fine with Chromedriver now, but it is still giving the same error for firefox: even though I changed the options carefully, is it working for firefox for you? I tried to use firefox by explicitly adding the path of geckodriver without using webdriver_manager and that is giving the same error too.

```
from selenium import webdriver
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.firefox.options import Options

options = Options()
options.add_argument('--proxy-server=%s' % proxy_url)
options.add_argument('--proxy-auto-detect')
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), options=options)
```
$ firefox --version
Mozilla Firefox 79.0

```
>>> import selenium
>>> from selenium.webdriver import Firefox
>>> driver = Firefox()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```
```
>>> driver = Firefox(executable_path="/usr/bin/geckodriver")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/anarang/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
```

**Comment by wblondel** [comment]
I tried on Fedora, I had the same problem as you.

```
[wblondel@localhost]$ firefox --version
Mozilla Firefox 79.0

[wblondel@localhost]$ which firefox
/usr/bin/firefox
```

But then I found something weird...
 ```
[wblondel@localhost]$ file $(which firefox)
/usr/bin/firefox: Bourne-Again shell script, ASCII text executable
```

The firefox "executable" that is in path on Fedora is actually not the real firefox executable, it is a wrapper! And Selenium apparently has some issues with that. This thread is from 2017 https://github.com/SeleniumHQ/selenium/issues/3884#issuecomment-296988595 but looks like the issue still exists.

If you give the real Firefox executable path to Selenium, it works fine.

```
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
from webdriver_manager.firefox import GeckoDriverManager
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary

firefox_options = FirefoxOptions()
firefox_options.headless = True

binary = FirefoxBinary('/usr/lib64/firefox/firefox')
driver = webdriver.Firefox(executable_path=GeckoDriverManager().install(), options=firefox_options, firefox_binary=binary)
```
