### ISSUE TITLE
Could not get version for Chrome with this command

### ISSUE THREAD

**Issue by NoahCardoza** [SergeyPirogov/webdriver_manager#146]
```text
/bin/sh: google-chrome: command not found
/bin/sh: google-chrome-stable: command not found
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from eventbrite import EventbriteBrowser, EventBriteClient
  File "/home/ec2-user/moodle-rest-bot/eventbrite.py", line 19, in <module>
    driver_path = ChromeDriverManager(version='85.0.4183.87').install()
  File "/home/ec2-user/.local/share/virtualenvs/moodle-rest-bot-j-oKnyNO/lib/python3.7/site-packages/webdriver_manager/chrome.py", line 28, in __init__
    chrome_type=chrome_type)
  File "/home/ec2-user/.local/share/virtualenvs/moodle-rest-bot-j-oKnyNO/lib/python3.7/site-packages/webdriver_manager/driver.py", line 54, in __init__
    self.browser_version = chrome_version(chrome_type)
  File "/home/ec2-user/.local/share/virtualenvs/moodle-rest-bot-j-oKnyNO/lib/python3.7/site-packages/webdriver_manager/utils.py", line 142, in chrome_version
    raise ValueError(f'Could not get version for Chrome with this command: {cmd}')
ValueError: Could not get version for Chrome with this command: google-chrome --version || google-chrome-stable --version
```

I'm trying to use this module on an AWS EC2 instance and while I understand the cause of this error, isn't the project's point to download a webdriver? If chrome hasn't been installed should that really halt the whole process? Shouldn't the lack of chrome be ignored and it continue to download the latest (or whatever version was specified) chrome driver?

Maybe there is a reason for this that I'm missing, but if not I'd like to look into submitting a PR to fix this (at least on linux).

Thanks for the otherwise very handy module! It's really saved me a lot of time generally speaking.

Noah

**Comment by SergeyPirogov** [comment]
@NoahCardoza Hello, what is a use case looks like? You don't have a Chrome browser, so why you want to download the driver? 
What driver version should be downloaded?

**Comment by AIGeneratedUsername** [comment]
@NoahCardoza why the issue is closed? Did you solve it? I have the same error.
