### ISSUE TITLE
Exceptions when trying to download driver

### ISSUE THREAD

**Issue by gs202** [SergeyPirogov/webdriver_manager#158]
After:
```
[WDM] - Current google-chrome version is 76.0.3809
[WDM] - Get LATEST driver version for 76.0.3809
[WDM] - There is no [linux64] chromedriver for browser 76.0.3809 in cache
[WDM] - Get LATEST driver version for 76.0.3809
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_linux64.zip
```
I get sporadicly the following: 
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/archive.py", line 19, in __extract_zip
    archive.extractall(to_directory)
  File "/usr/lib/python3.6/zipfile.py", line 1524, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.6/zipfile.py", line 1577, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib/python3.6/zipfile.py", line 1393, in open
    raise BadZipFile("Truncated file header")
zipfile.BadZipFile: Truncated file header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/tests/fixtures/webdriver.py", line 66, in web_driver_path
    return selenium_driver.install()
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/manager.py", line 31, in _get_driver_path
    driver_name, os_type, driver_version)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/driver_cache.py", line 28, in save_file_to_cache
    files = archive.unpack(path)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/archive.py", line 12, in unpack
    return self.__extract_zip(directory)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_us1/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/archive.py", line 21, in __extract_zip
    if e.args[0] not in [26, 13] and e.args[1] not in ['Text file busy', 'Permission denied']:
IndexError: tuple index out of range
```
and sometimes:
```
Traceback (most recent call last):
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_eu2/tests/fixtures/webdriver.py", line 66, in web_driver_path
    return selenium_driver.install()
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_eu2/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/chrome.py", line 32, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_eu2/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/manager.py", line 31, in _get_driver_path
    driver_name, os_type, driver_version)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_eu2/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/driver_cache.py", line 28, in save_file_to_cache
    files = archive.unpack(path)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_eu2/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/archive.py", line 12, in unpack
    return self.__extract_zip(directory)
  File "/home/jenkins/workspace/execute_shield_inigo_ui_login_eu2/.eggs/webdriver_manager-3.2.2-py3.6.egg/webdriver_manager/archive.py", line 17, in __extract_zip
    archive = zipfile.ZipFile(self.file_path)
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by ToStefan** [comment]
@SergeyPirogov What is the solution for this? I came on same problem.

`driver = webdriver.Chrome(options=options, executable_path=driver_manager.install(),
File "/usr/local/lib/python3.8/dist-packages/webdriver_manager/chrome.py", line 32, in install
driver_path = self._get_driver_path(self.driver)
File "/usr/local/lib/python3.8/dist-packages/webdriver_manager/manager.py", line 30, in _get_driver_path
binary_path = self.driver_cache.save_file_to_cache(file, browser_version,
File "/usr/local/lib/python3.8/dist-packages/webdriver_manager/driver_cache.py", line 28, in save_file_to_cache
files = archive.unpack(path)
File "/usr/local/lib/python3.8/dist-packages/webdriver_manager/archive.py", line 12, in unpack
return self.__extract_zip(directory)
File "/usr/local/lib/python3.8/dist-packages/webdriver_manager/archive.py", line 17, in __extract_zip
archive = zipfile.ZipFile(self.file_path)
File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
self._RealGetContents()
File "/usr/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

**Comment by SergeyPirogov** [comment]
@ToStefan which version you are trying to download? Which version of the browser do you have?

**Comment by ToStefan** [comment]
@SergeyPirogov 
I have 3.2.2 version of webdriver-manager
Version of my Google Chrome is 85.0.4183.83

Executed code:

```
		driver_manager = ChromeDriverManager(log_level=logging.WARNING,
												cache_valid_range=15)
		driver = webdriver.Chrome(options=options, executable_path=driver_manager.install(),
									desired_capabilities=capabilities)
```

**Comment by ToStefan** [comment]
I think updating browser or setting "--no-sandbox" option solved our problem.

**Comment by petrisorionel** [comment]
Hello, any idea how to fix this? I added the --no-sandbox option to Chrome.

https://github.com/SergeyPirogov/webdriver_manager/issues/290
