### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by lesanpi** [SergeyPirogov/webdriver_manager#183]
I dont know why is happening this error.
My code is a simple hello world with selenium and webdriver_manager

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
driver = webdriver.Chrome(ChromeDriverManager().install())

====== WebDriver manager ======
Current google-chrome version is 90.0.4430
Get LATEST driver version for 90.0.4430
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriver_manager\chrome.py", line 34, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriver_manager\manager.py", line 25, in _get_driver_path
    binary_path = self.driver_cache.find_driver(browser_version, driver_name, os_type,
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriver_manager\driver_cache.py", line 66, in find_driver
    metadata = self.get_metadata()
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\site-packages\webdriver_manager\driver_cache.py", line 91, in get_metadata
    return json.load(outfile)
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\lespi\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lesanpi** [comment]
I solved this problem deleting .wdm directory in C:\Users\[your user] path
