### ISSUE TITLE
WinError6 while executing script, packed in .exe by pyinstaller

### ISSUE THREAD

**Issue by OlehBedrii** [SergeyPirogov/webdriver_manager#204]
Hello, 

I was trying to run the app, but some errors appear during the execution, if I create the .exe in console-less mode.
If console remains, code works fine. 

In short, my code looks like this:
```
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

def run():
    driver = webdriver.Chrome(ChromeDriverManager().install())
    driver.get("https://www.google.com/")
    driver.quit()

run()
```

Here is how I created .exe file with pyinstaller:
```
pyinstaller --onefile --w script.py
```

This is the error that appears:
```
Traceback (most recent call last): 
File "script.py", line 5, in run
File "webdriver_manager\chrome.py", line 30, in __init__ 
File "webdriver_manager\driver.py", line 57, in __init__
File "webdriver_manager\utils.py", line 150, in chrome_version
File "os.py", line 989, in popen
File "subprocess.py", line 709, in __init__
File "subprocess.py", line 1006, in _get_handles
OSError: [WinError 6] The handle is invalid
```

At first I thought it is somehow related to logs, as discussed in the issue #196 , but the advise from there did not help for the application packed in .exe

Would be glad for help. 
Thanks.

**Comment by OlehBedrii** [comment]
Ok, I see that the latest commit #198  supposed to fix that, but it's not yet officially published. 
I'm still on version 3.4.2

**Comment by OlehBedrii** [comment]
I close the issue, because bug is fixed as mentioned in comment before (checked in my code), but not yet released in pypi.
