### ISSUE TITLE
ValueError: Version must consist of major, minor and/or patch, but given was: .3.150.2 

### ISSUE THREAD

**Issue by ArunDruk** [SergeyPirogov/webdriver_manager#221]
[WDM] - There is no [x64] IEDriverServer for browser  in cache
Traceback (most recent call last):
  File "C:/Users/akumar6/PycharmProjects/Practice_programs/Selenium_pgms/IE_pgm1.py", line 8, in <module>
    driver=webdriver.Ie(IEDriverManager().install())
  File "C:\Users\akumar6\AppData\Local\Programs\Python\Python38-32\lib\site-packages\webdriver_manager\microsoft.py", line 26, in install
    return self._get_driver_path(self.driver)
  File "C:\Users\akumar6\AppData\Local\Programs\Python\Python38-32\lib\site-packages\webdriver_manager\manager.py", line 29, in _get_driver_path
    file = download_file(driver.get_url())
  File "C:\Users\akumar6\AppData\Local\Programs\Python\Python38-32\lib\site-packages\webdriver_manager\driver.py", line 168, in get_url
    major, minor, patch = self.__get_divided_version(self.get_version())
  File "C:\Users\akumar6\AppData\Local\Programs\Python\Python38-32\lib\site-packages\webdriver_manager\driver.py", line 181, in __get_divided_version
    raise ValueError(
ValueError: Version must consist of major, minor and/or patch, but given was: .3.150.2

Process finished with exit code 1

Am trying to run the below code in 64 bit, windows 10 pro:

from webdriver_manager.microsoft import IEDriverManager
driver=webdriver.Ie(IEDriverManager().install())

**Comment by cashewleaf** [comment]
The issue I posted in Selenium side is of the same cause. 
https://github.com/SeleniumHQ/selenium/issues/9787

You can detour the problem itself by using locally downloaded module from the following URL.
https://github.com/SeleniumHQ/selenium/releases/download/selenium-3.150.0/IEDriverServer_Win32_3.150.2.zip

I need to note that .exe file of IEDriverServer_Win32_3.150.1 and IEDriverServer_Win32_3.150.2 are not totally
same in compatibility. I am still checking behavior change of these two.

**Comment by aleksandr-kotlyar** [comment]
@cashewleaf 
> I need to note that .exe file of IEDriverServer_Win32_3.150.1 and IEDriverServer_Win32_3.150.2 are not totally
same in compatibility. I am still checking behavior differences of these two.

Seems they should not be. Because selenium hasn't released 3.150.x versions for python. So they can not work. Try use 3.141.0 or 3.141.59 version for IE. I think they should work.
