### ISSUE TITLE
Failed to Download the Edge driver for particular Version

### ISSUE THREAD

**Issue by AnithaSyed** [SergeyPirogov/webdriver_manager#251]
Hi, 
I have been facing problems on downloading the chrome driver while using web driver manager and I raised issues before.
Now I switched to use the Edge driver to work and it's working fine while I test in console, but When I try with Jenkins it is unable to download the driver.
Now I manually giving the suitable version as a input to download the driver but still i am seeing the same error.
My Code is:
```
import os, time
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.microsoft import EdgeChromiumDriverManager
from selenium.webdriver.edge.options import Options
from selenium.webdriver.edge.service import Service

chrome_options = Options()
prefs = {'safebrowsing.enabled': 'false','download.default_directory' : os.getcwd() + os.path.sep}
chrome_options.add_experimental_option("prefs", prefs)
chrome_options.add_experimental_option("useAutomationExtension", False)
chrome_options.add_argument('headless')

driver = webdriver.Edge(service = Service(EdgeChromiumDriverManager(edgevesion()).install()), options = chrome_options)

driver.get (url)
```

Here `edgevesion()` will give the browser version as output

I got the error as:

```
[WDM] - ====== WebDriver manager ======
Traceback (most recent call last):
  File "Edge_cov.py", line 317, in <module>
    driver = webdriver.Edge(service = Service(EdgeChromiumDriverManager(edgevesion()).install()), options = chrome_options)
  File "webdriver_manager\microsoft.py", line 51, in __init__
  File "webdriver_manager\driver.py", line 282, in __init__
  File "webdriver_manager\utils.py", line 159, in get_browser_version_from_os
ValueError: Could not get version for edge with the command: reg query "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Edge\BLBeacon" /v version
[26368] Failed to execute script 'Edge_cov' due to unhandled exception!
```
Since I gave the version, it has to download it, but it is checking the version again.
Please help me on this What I did wrong

**Comment by AnithaSyed** [comment]
I see the #260 is mentioned as a resolve for my issue and it is merged too.
But I am still facing the issue. So is it released yet?

**Comment by aleksandr-kotlyar** [comment]
@AnithaSyed code is in master branch but 3.5.2 not released yet.

**Comment by AnithaSyed** [comment]
@aleksandr-kotlyar 
I passed the version as '94.0.992.38'

but I am getting below error

  ```
File "C:\Users\qjq2g6\Anaconda3\lib\site-packages\webdriver_manager\logger.py", line 19, in _init_logger
    _logger.setLevel(level)

  File "C:\Users\qjq2g6\Anaconda3\lib\logging\__init__.py", line 1421, in setLevel
    self.level = _checkLevel(level)

  File "C:\Users\qjq2g6\Anaconda3\lib\logging\__init__.py", line 201, in _checkLevel
    raise TypeError("Level not an integer or a valid string: %r" % level)

TypeError: Level not an integer or a valid string: None
```
