### ISSUE TITLE
Issue with latest version of Chrome Version 96.0.4664.45 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by rsclmumbai** [SergeyPirogov/webdriver_manager#275]
Webdriver-Manager 3.5.2

With the latest version of Chrome 96.0.4664.45 (Official Build) (64-bit) I'm getting the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "help.py", line 141, in Operate
  File "help.py", line 154, in MakeOperations
  File "help.py", line 114, in createDriver_chrome
  File "site-packages\webdriver_manager\chrome.py", line 32, in install
  File "site-packages\webdriver_manager\manager.py", line 29, in _get_driver_path
  File "site-packages\webdriver_manager\utils.py", line 93, in download_file
  File "site-packages\webdriver_manager\utils.py", line 79, in validate_response
ValueError: There is no such driver by url http://chromedriver.storage.googleapis.com//chromedriver_win32.zip

How can I fix this?

**Comment by Crateio1stLevelSupport** [comment]
Please delete this issue. It was an update problem at my end. 
Apologies!

**Comment by rsclmumbai** [comment]
Please delete this issue. It was an update problem at my end.
Apologies!

**Comment by aleksandr-kotlyar** [comment]
@rsclmumbai you can close it by yourself. ;-)
