### ISSUE TITLE
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 98 Current browser version is 96.0.4650.0 with binary path /home/USER/.local/bin/chrome

### ISSUE THREAD

**Issue by shaenr** [SergeyPirogov/webdriver_manager#295]
First of all, I realize that I I could easily upgrade the browser to 98 and probably should. This installation of Chrome 96 is not something I actually use. The idea behind using this webdriver_manager is that I want my script to work with as many different browser versions as possible because I can't depend on every user to keep their browser updated.

Here is the relevant code that errors, which is provided in full below as well.

```py
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

def get_driver(binary_location: str):
    options = webdriver.ChromeOptions()
    options.add_argument('--ignore-certificate-errors')
    options.add_argument('--test-type')
    options.add_argument("--disable-notifications")
    options.add_argument("--remote-debugging-port=9225");
    options.binary_location = binary_location
    service = Service(ChromeDriverManager().install())
    return webdriver.Chrome(service=service, options=options)
```

Thank you for taking the time to look at this.

The error:

```
====== WebDriver manager ======
Could not get version for google-chrome with the any command: google-chrome --version || google-chrome-stable --version
Current google-chrome version is UNKNOWN
Get LATEST chromedriver version for UNKNOWN google-chrome
Driver [/home/shaen/.wdm/drivers/chromedriver/linux64/98.0.4758.80/chromedriver] found in cache
Traceback (most recent call last):
  File "/home/shaen/bandcamp-flac-get/main.py", line 111, in <module>
    with get_driver(CHROME_BINARY) as driver:
  File "/home/shaen/bandcamp-flac-get/main.py", line 42, in get_driver
    return webdriver.Chrome(service=service, options=options)
  File "/home/shaen/bandcamp-flac-get/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/shaen/bandcamp-flac-get/venv/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/shaen/bandcamp-flac-get/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/shaen/bandcamp-flac-get/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/shaen/bandcamp-flac-get/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/home/shaen/bandcamp-flac-get/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 98
Current browser version is 96.0.4650.0 with binary path /home/shaen/.local/bin/chrome
Stacktrace:
#0 0x56396bc90113 <unknown>
#1 0x56396b7586d8 <unknown>
#2 0x56396b77f575 <unknown>
#3 0x56396b77adcc <unknown>
#4 0x56396b77719a <unknown>
#5 0x56396b7b1e0a <unknown>
#6 0x56396b7abf53 <unknown>
#7 0x56396b781bda <unknown>
#8 0x56396b782ca5 <unknown>
#9 0x56396bcc18dd <unknown>
#10 0x56396bcdaa9b <unknown>
#11 0x56396bcc36b5 <unknown>
#12 0x56396bcdb725 <unknown>
#13 0x56396bcb708f <unknown>
#14 0x56396bcf8188 <unknown>
#15 0x56396bcf8308 <unknown>
#16 0x56396bd12a6d <unknown>
#17 0x7f18459bd450 <unknown>


Process finished with exit code 1
```

**Comment by shaenr** [comment]
btw this would have worked 

```
$ chrome --version
Chromium 96.0.4650.0 
```

**Comment by aleksandr-kotlyar** [comment]
@shaenr thank you for detailed report!
Please look at this part of  [Readme.md](https://github.com/SergeyPirogov/webdriver_manager/blob/master/README.md) 

https://github.com/SergeyPirogov/webdriver_manager/blob/eabc7b6605cfd51114ea9785ec1c57bbd9be939d/README.md#L51-L59

**Comment by shaenr** [comment]
Ah, thank you. I am silly.

**Comment by aleksandr-kotlyar** [comment]
No problem.
