### ISSUE TITLE
EdgeChromiumDriverManager.install fails in 3.5.3 when no Edge found

### ISSUE THREAD

**Issue by JoriDubrovin** [SergeyPirogov/webdriver_manager#312]
On an Intel Mac with Edge browser not installed, EdgeChromiumDriverManager.install raises
`ValueError: There is no such driver by url https://msedgedriver.azureedge.net/LATEST_RELEASE`

Seems that this line in drivers.py does not work as intended:
```
       self._latest_release_url.replace('LATEST_RELEASE', 'LATEST_STABLE')
```

**Comment by aleksandr-kotlyar** [comment]
Give more info to reproduce please

1. What version of OS?
2. What version of Edge?
3. What path Edge is installed to?
3. What platform architecture?
4. Code example to reproduce

**Comment by JoriDubrovin** [comment]
Hi, this is on macOS 12.2.1, 2 GHz Quad-Core Intel Core i5.

Edge is not installed.

To reproduce, setup:
```
jori@Jori-MBP repro % python3.9 -m venv venv
jori@Jori-MBP repro % source venv/bin/activate
(venv) jori@Jori-MBP repro % pip install webdriver-manager==3.5.3
```
Code:
```
(venv) jori@Jori-MBP repro % cat repro.py
from webdriver_manager.microsoft import EdgeChromiumDriverManager

EdgeChromiumDriverManager(path='.').install()
```
Actual results:
```
(venv) jori@Jori-MBP repro % python repro.py
[WDM] - ====== WebDriver manager ======
[WDM] - Could not get version for edge with the command: /Applications/Microsoft\ Edge.app/Contents/MacOS/Microsoft\ Edge --version
[WDM] - Current edge version is UNKNOWN
Traceback (most recent call last):
  File "/Users/jori/repro/repro.py", line 3, in <module>
    EdgeChromiumDriverManager(path='.').install()
  File "/Users/jori/repro/venv/lib/python3.9/site-packages/webdriver_manager/microsoft.py", line 61, in install
    driver_path = self._get_driver_path(self.driver)
  File "/Users/jori/repro/venv/lib/python3.9/site-packages/webdriver_manager/manager.py", line 23, in _get_driver_path
    driver_version = driver.get_version()
  File "/Users/jori/repro/venv/lib/python3.9/site-packages/webdriver_manager/driver.py", line 40, in get_version
    return self.get_latest_release_version()
  File "/Users/jori/repro/venv/lib/python3.9/site-packages/webdriver_manager/driver.py", line 316, in get_latest_release_version
    else self.get_stable_release_version()
  File "/Users/jori/repro/venv/lib/python3.9/site-packages/webdriver_manager/driver.py", line 308, in get_stable_release_version
    validate_response(resp)
  File "/Users/jori/repro/venv/lib/python3.9/site-packages/webdriver_manager/utils.py", line 80, in validate_response
    raise ValueError("There is no such driver by url {}".format(resp.url))
ValueError: There is no such driver by url https://msedgedriver.azureedge.net/LATEST_RELEASE
```

**Comment by JoriDubrovin** [comment]
Current master (commit acf72e019b30) works for me: running `EdgeChromiumDriverManager(path='.').install()` installs the latest msedgedriver if Edge browser is not installed.

Thank you!

**Comment by aleksandr-kotlyar** [comment]
@JoriDubrovin Thank you for your feedback!
