### ISSUE TITLE
Error: Cannot find chrome binary

### ISSUE THREAD

**Issue by reisenmachtfreude** [SergeyPirogov/webdriver_manager#368]
I'm trying to run the example code for brave, but it results in the following error:
```
Python 3.9.7 (default, Sep 10 2021, 14:59:43) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from selenium import webdriver
>>> from selenium.webdriver.chrome.service import Service
>>> from webdriver_manager.chrome import ChromeDriverManager
>>> from webdriver_manager.utils import ChromeType
>>> 
>>> driver = webdriver.Chrome(service=Service(ChromeDriverManager(chrome_type=ChromeType.BRAVE).install()))


====== WebDriver manager ======
Current brave-browser version is 100
Get LATEST chromedriver version for 100 brave-browser
There is no [linux64] chromedriver for browser 100 in cache
Trying to download new driver from https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_linux64.zip
Driver has been saved in cache [/home/pong.wdm/drivers/chromedriver/linux64/100.0.4896.60]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pong.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/pong.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "/home/pong.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pong.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pong.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/home/pong.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x55efc7da0ad3 <unknown>
#1 0x55efc7b00568 <unknown>
#2 0x55efc7b21a59 <unknown>
#3 0x55efc7b1f23a <unknown>
#4 0x55efc7b5a2ba <unknown>
#5 0x55efc7b544e3 <unknown>
#6 0x55efc7b29d1a <unknown>
#7 0x55efc7b2ae75 <unknown>
#8 0x55efc7dceefd <unknown>
#9 0x55efc7de819b <unknown>
#10 0x55efc7dd0c65 <unknown>
#11 0x55efc7de8ec8 <unknown>
#12 0x55efc7dc4360 <unknown>
#13 0x55efc7e04a68 <unknown>
#14 0x55efc7e04be8 <unknown>
#15 0x55efc7e1e7fd <unknown>
#16 0x7f6de93d6947 <unknown>

>>> 
```

I'm using Ubuntu Ubuntu 21.10.
```
pip3 show webdriver-manager
Name: webdriver-manager
Version: 3.5.4
Summary: Library provides the way to automatically manage drivers for different browsers
Home-page: https://github.com/SergeyPirogov/webdriver_manager
Author: Sergey Pirogov
Author-email: automationremarks@gmail.com
License: UNKNOWN
Location: /home/ping/.local/lib/python3.9/site-packages
Requires: requests
Required-by: 
```

**Comment by aleksandr-kotlyar** [comment]
@reisenmachtfreude hi!
I see you need to tell the Selenium where is your Brave binary is.
Look at the example:

https://github.com/SergeyPirogov/webdriver_manager/blob/259cfdba30493c8835cba746683b0f14caefe0cf/tests/test_brave_driver.py#L32-L41

You need to pass brave binary path to options.binary_location and then create the Selenium webdriver with this option

**Comment by reisenmachtfreude** [comment]
Thank You Aleksandr! It works now.

I've learned that Selenium not only need to have a driver installed (with your webdriver-manager). Additionally it always needs access to browser binary of the system.

**Comment by aleksandr-kotlyar** [comment]
@reisenmachtfreude you are welcome! Issue solved?

**Comment by reisenmachtfreude** [comment]
Yes, issue closed.
