### ISSUE TITLE
Brave Browser fails to launch after running selenium on win32

### ISSUE THREAD

**Issue by gathuaalex** [SergeyPirogov/webdriver_manager#384]
**This is the code am running and stacktrace . Any help will be appreciated, Thank you in advance.**

   ```
 options= webdriver.ChromeOptions()
    options.binary_location = "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe"
    options.headless = self.headless
    options.add_argument('--no-sandbox')
    options.add_argument('--window-size=1100,1000')
    options.add_argument('--single-process')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument("--incognito")
    options.add_argument('--disable-blink-features=AutomationControlled')
    options.add_experimental_option('useAutomationExtension', False)
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_argument("disable-infobars")
    options.add_argument('user-agent={}'.format(UserAgent().random))
    if selenium_driver:
    self.driver = selenium_driver
    else:
    # self.driver = webdriver.Remote(
    #     command_executor=command_executor_url,
    #     options=options
    #
    # )
    service = Service(ChromeDriverManager(chrome_type=ChromeType.BRAVE).install())
    self.driver = webdriver.Chrome(service=service, options=options)

```

The stacktrace 
```
[WDM] - ====== WebDriver manager ======
[WDM] - Current brave-browser version is 102
[WDM] - Get LATEST chromedriver version for 102 brave-browser
[WDM] - Driver [C:\Users\Alex\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache
[16972:8164:0527/013447.920:ERROR:system_network_context_manager.cc(758)] Cannot use V8 Proxy resolver in single process mode.
[16972:8164:0527/013448.016:ERROR:system_network_context_manager.cc(758)] Cannot use V8 Proxy resolver in single process mode.
[16972:8164:0527/013448.056:ERROR:system_network_context_manager.cc(758)] Cannot use V8 Proxy resolver in single process mode.

DevTools listening on ws://127.0.0.1:55817/devtools/browser/63e53c01-d753-4c25-8a17-d92e1b71aeaf
[16972:8164:0527/013448.152:ERROR:system_network_context_manager.cc(758)] Cannot use V8 Proxy resolver in single process mode.
Internal Server Error: /test/
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "F:\PROJECTS\legits_scrapper\core\views.py", line 147, in index
    obj = StudyBay(
  File "F:\PROJECTS\legits_scrapper\utils\study_bay_pool.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "F:\PROJECTS\legits_scrapper\utils\base_paper_entry.py", line 83, in __init__
    self.set_selenium_remote_session(
  File "F:\PROJECTS\legits_scrapper\utils\base_paper_entry.py", line 197, in set_selenium_remote_session
    self.driver = webdriver.Chrome(service=service, options=options)
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 275, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 365, in start_sessi
on
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Alex\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_re
sponse
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: crashed.
  (chrome not reachable)
  (The process started from chrome location C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
Backtrace:
        Ordinal0 [0x011ED953+2414931]
        Ordinal0 [0x0117F5E1+1963489]
        Ordinal0 [0x0106C6B8+837304]
        Ordinal0 [0x01089BD4+957396]
        Ordinal0 [0x01085FB1+942001]
        Ordinal0 [0x010B9100+1151232]
        Ordinal0 [0x010B8D5A+1150298]
        Ordinal0 [0x010B42B6+1131190]
        Ordinal0 [0x0108E860+976992]
        Ordinal0 [0x0108F756+980822]
        GetHandleVerifier [0x0145CC62+2510274]
        GetHandleVerifier [0x0144F760+2455744]
        GetHandleVerifier [0x0127EABA+551962]
        GetHandleVerifier [0x0127D916+547446]
        Ordinal0 [0x01185F3B+1990459]
        Ordinal0 [0x0118A898+2009240]
        Ordinal0 [0x0118A985+2009477]
        Ordinal0 [0x01193AD1+2046673]
        BaseThreadInitThunk [0x76436739+25]
        RtlGetFullPathName_UEx [0x77D78FEF+1215]
        RtlGetFullPathName_UEx [0x77D78FBD+1165]
```

**Comment by aleksandr-kotlyar** [comment]
Driver has been found in cache.
> [WDM] - Driver [C:\Users\Alex\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache
that means that webdriver-manager works fine. And thats the end of webdriver-manager work here. 

You have a problem somewhere in django/selenium/your machine. 
You have a row in stacktrace 
>  (The process started from chrome location C:\Program Files\BraveSoftware\Brave-Browser\Application\brave.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

You have to find out why your Brave browser crashes on your machine.
Please take a look at this row:
> Cannot use V8 Proxy resolver in single process mode.

Chromium did nothing with this bug for 8 years. https://bugs.chromium.org/p/chromium/issues/detail?id=474698
Removing `--single-process` from options in your code will probably fix the issue.

**Comment by gathuaalex** [comment]
I investigated the issue and found i had added this optional argument
`options.add_argument('--single-process')`
I commented  it out and  brave got launched 🥳🥳🥳🥳🥳.
