### ISSUE TITLE
can not install the driver as there is no https://api.github.com/repos/mozilla/geckodriver/releases/latest

### ISSUE THREAD

**Issue by HamedMinaeizaeim** [SergeyPirogov/webdriver_manager#385]
``[WDM] - ====== WebDriver manager ======

[WDM] - Current firefox version is 88.0
[WDM] - Get LATEST geckodriver version for 88.0 firefox
[WDM] - GH_TOKEN will be used to perform requests
Traceback (most recent call last):
  File "C:/Users/Hamed/PycharmProjects/twitter_crypto_api/venv/main.py", line 15, in <module>
    get_data_coinmarket()
  File "C:/Users/Hamed/PycharmProjects/twitter_crypto_api/venv/main.py", line 9, in get_data_coinmarket
    data = coin.extract3PagecoinData()
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\src\crypto_selenum.py", line 80, in extract3PagecoinData
    self.setupDriver()
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\src\crypto_selenum.py", line 29, in setupDriver
    self.driver = driver_initilizer.set_driver_for_browser()
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\src\driver_initialisation.py", line 69, in set_driver_for_browser
    return webdriver.Firefox(executable_path=GeckoDriverManager().install(),
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\firefox.py", line 35, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\core\manager.py", line 27, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\core\driver_cache.py", line 88, in find_driver
    driver_version = driver.get_version()
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\core\driver.py", line 43, in get_version
    if self._version == "latest"
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\drivers\firefox.py", line 33, in get_latest_release_version
    headers=self.auth_header
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\core\http.py", line 30, in get
    self.validate_response(resp)
  File "C:\Users\Hamed\PycharmProjects\twitter_crypto_api\venv\lib\site-packages\webdriver_manager\core\http.py", line 18, in validate_response
    f"response body:\n{resp.text}\n"
ValueError: response body:
{"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
request url:
https://api.github.com/repos/mozilla/geckodriver/releases/latest
response headers:
{'Server': 'GitHub.com', 'Date': 'Sat, 28 May 2022 04:21:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '80', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '59', 'X-RateLimit-Reset': '1653715307', 'X-RateLimit-Used': '1', 'X-RateLimit-Resource': 'core', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Frame-Options': 'deny', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '0', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'Content-Security-Policy': "default-src 'none'", 'Vary': 'Accept-Encoding, Accept, X-Requested-With', 'X-GitHub-Request-Id': 'FD17:1794:368312:3A8294:6291A35B'}

**Comment by Pavocracy** [comment]
Do you have an example of the code you used that triggered this error?

As the response body is suggesting, there is an auth issue going on here. Do you have a GH_TOKEN env variable set?

**Comment by testttt0** [comment]
I am experiencing the same issue in China. I believe it has something to do with the GFW. And I managed to solve it by using a mirror site.

`# use npmmirror.com
import requests
def get_geckodriver_latest_ver(self):
    j = requests.get('https://registry.npmmirror.com/-/binary/geckodriver/').json()
    vers = [x['name'].strip('/') for x in j if x['type']=='dir']
    vers = sorted(vers, key=lambda x:[int(i) for i in x.strip('v').split('.')], reverse=True)
    return vers[0]
def get_geckodriver_download_url(self):
    j = requests.get(f"https://registry.npmmirror.com/-/binary/geckodriver/{self.get_version()}/").json()
    name = f"{self.get_name()}-{self.get_version()}-{self.get_os_type()}."
    output_url = [x['url'] for x in j if x['type']=='file' and x['name'].startswith(name)]
    return output_url[0]
from webdriver_manager.drivers.firefox import GeckoDriver
GeckoDriver.get_latest_release_version = get_geckodriver_latest_ver
GeckoDriver.get_url = get_geckodriver_download_url

# selenium 4
from selenium import webdriver
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager

geckodriver_manager = GeckoDriverManager()
driver = webdriver.Firefox(service=Service(geckodriver_manager.install()))`

**Comment by help1234** [comment]
me the same error with chromedriver version in china, also fixed by rewrite the function with a mirrow site ,
