### ISSUE TITLE
Use cached version when reaching GitHub api rate limited error

### ISSUE THREAD

**Issue by eyaler** [SergeyPirogov/webdriver_manager#415]
cached version not used on rate limited error (but if i disconnect from the internet it does work). i would like the cache version to work for any connection error.

to recreate:
```
from webdriver_manager.firefox import GeckoDriverManager
for i in range(100): GeckoDriverManager(cache_valid_range=0).install()
```

2022-07-19 02:00:22,187 - WDM - INFO - ====== WebDriver manager ======
2022-07-19 02:00:23,530 - WDM - INFO - Get LATEST geckodriver version for 102.0 firefox
2022-07-19 02:00:23,533 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-07-19 02:00:25,479 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 3019
2022-07-19 02:00:26,879 - WDM - INFO - Driver [C:\Users\eyaler\.wdm\drivers\geckodriver\win64\0.31\geckodriver.exe] found in cache
'C:\\Users\\eyaler\\.wdm\\drivers\\geckodriver\\win64\\0.31\\geckodriver.exe'
>>> GeckoDriverManager().install()

2022-07-19 02:00:42,819 - WDM - INFO - ====== WebDriver manager ======
2022-07-19 02:00:44,090 - WDM - INFO - Get LATEST geckodriver version for 102.0 firefox
2022-07-19 02:00:44,093 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-07-19 02:00:45,761 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 200 3021
2022-07-19 02:00:47,034 - WDM - INFO - Driver [C:\Users\eyaler\.wdm\drivers\geckodriver\win64\0.31\geckodriver.exe] found in cache
'C:\\Users\\eyaler\\.wdm\\drivers\\geckodriver\\win64\\0.31\\geckodriver.exe'
>>> GeckoDriverManager().install()

2022-07-19 02:01:01,355 - WDM - INFO - ====== WebDriver manager ======
2022-07-19 02:01:02,619 - WDM - INFO - Get LATEST geckodriver version for 102.0 firefox
2022-07-19 02:01:02,622 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-07-19 02:01:02,739 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 403 281
2022-07-19 02:01:05,243 - WDM - INFO - There is no [win64] geckodriver for browser 102.0 in cache
2022-07-19 02:01:06,497 - WDM - INFO - Get LATEST geckodriver version for 102.0 firefox
2022-07-19 02:01:06,500 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-07-19 02:01:06,618 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 403 281
2022-07-19 02:01:07,871 - WDM - INFO - Getting latest mozilla release info for 102.0
2022-07-19 02:01:09,113 - WDM - INFO - Get LATEST geckodriver version for 102.0 firefox
2022-07-19 02:01:09,116 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-07-19 02:01:09,215 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/latest HTTP/1.1" 403 281
2022-07-19 02:01:10,476 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-07-19 02:01:10,589 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla/geckodriver/releases/tags/102.0 HTTP/1.1" 403 281
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\webdriver_manager\firefox.py", line 36, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Python39\lib\site-packages\webdriver_manager\core\manager.py", line 31, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "C:\Python39\lib\site-packages\webdriver_manager\drivers\firefox.py", line 40, in get_url
    resp = self._http_client.get(
  File "C:\Python39\lib\site-packages\webdriver_manager\core\http.py", line 32, in get
    self.validate_response(resp)
  File "C:\Python39\lib\site-packages\webdriver_manager\core\http.py", line 19, in validate_response
    raise ValueError(
ValueError: response body:
{"message":"API rate limit exceeded for 157.131.251.165. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

request url:
https://api.github.com/repos/mozilla/geckodriver/releases/tags/102.0
response headers:
{'Date': 'Tue, 19 Jul 2022 09:01:13 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1658223742', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '281', 'X-GitHub-Request-Id': 'C5A0:80DE:2D986D:359096:62D672D9'}

**Comment by mere-human** [comment]
Same as https://github.com/SergeyPirogov/webdriver_manager/issues/442

**Comment by eyaler** [comment]
@aleksandr-kotlyar this issue was actually about an enhancement where i asked for allowing me to fallback to an INVALID cache if I hit the rate limit
