### ISSUE TITLE
Install driver on debian 11 server: selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

### ISSUE THREAD

**Issue by reisenmachtfreude** [SergeyPirogov/webdriver_manager#426]
I'm running Python 3.9.2, Selenium 4.3.0 on Debian 11 VPS (via SSH).

The installation is copied from README:
```
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager
driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
```
The following error message appears:
```
[WDM] - Downloading: 16.2kB [00:00, 8.56MB/s]                                                        
[WDM] - Downloading: 100%|██████████████████████████████████████| 2.59M/2.59M [00:00<00:00, 5.35MB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myuser/.local/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 177, in __init__
    super().__init__(
  File "/home/myuser/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 277, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/myuser/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 370, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/myuser/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 435, in execute
    self.error_handler.check_response(response)
  File "/home/myuser/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

A file was stored to /home/myuser/.wdm/drivers/geckodriver/linux64/0.31/geckodriver
However, if I execute a python script:
```
from selenium import webdriver
d = webdriver.Firefox()
```
The error is shown:
`selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. 
`

Thanks for your help

**Comment by bloedrivier** [comment]
Even if you add the path like this `export PATH=$PATH:/path/to/directory/of/geckodriver/` which should be something like `/home/user/.wdm/drivers/` if you used `driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))`... the next error will be:

```
Traceback (most recent call last):
  File "/home/user/.virtualenvs/proj/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/proj/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/home/user/.virtualenvs/proj/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions.
```

even the permissions on the file are set to
`
ls -lh /home/user/.wdm/drivers/
total 4.0K
drwxrwxr-x 3 user user 4.0K Aug 19 18:59 geckodriver
`

**Comment by bloedrivier** [comment]
Even if you add ` /home/myuser/.wdm/drivers/geckodriver/linux64/0.31/geckodriver` to `$PATH:path` or `path:$PATH` error persists.

In the geckodriver.log, you can see this:
```
1660932893308   geckodriver     INFO    Listening on 127.0.0.1:59639
1660932893824   mozrunner::runner       INFO    Running command: "/usr/bin/firefox" "--marionette" "--remote-debugging-port" "45169" "--remote-allow-hosts" "localhost" "-no-remote" "-profile" "/tmp/rust_mozprofileznUvZa"
Error: no DISPLAY environment variable specified
```

but the headless option has been set?

```
if platform == "linux":
    options = Options()
    #options.add_argument("-headless")
    options.headless = True
    options.add_experimental_option("prefs", {
        "download.default_directory": "/home/user/projects/",
        "download.prompt_for_download": False,
        "download.directory_upgrade": True,
        "safebrowsing_for_trusted_sources_enabled": False,
        "safebrowsing.enabled": False
    })
    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
```

**Comment by bloedrivier** [comment]
Fixed:

```
from selenium import webdriver

from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service

from webdriver_manager.firefox import GeckoDriverManager

options = Options()
options.set_preference('profile', '/home/user/.mozilla/firefox/bra7r0kl.default-release')
options.binary = "/usr/bin/firefox"
options.add_argument("-headless")
driver = webdriver.Firefox(service=Service(GeckoDriverManager().install()), options=options)
```
