### ISSUE TITLE
webdriver manager on raspberry pi

### ISSUE THREAD

**Issue by ziza88** [SergeyPirogov/webdriver_manager#432]
Hi,
I am trying to use selenium and webdriver manager on my Raspberry Pi 3 Model B.

I used this:
```from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromiumService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import ChromeType

driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))

driver.get('www.google.de')
```

This was the output:
```
Traceback (most recent call last):
  File "/home/pi/MyTest/05_EbKl/test.py", line 7, in <module>
    driver = webdriver.Chrome(service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()))
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 89, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/pi/.wdm/drivers/chromedriver/linux64/101.0.4951/chromedriver'
```

And here are some further infos:
```
chromium-browser --version
Chromium 101.0.4951.57 Built on Debian , running on Debian 11
```
```
uname -a
Linux raspberrypi 5.15.56-v8+ #1575 SMP PREEMPT Fri Jul 22 20:31:26 BST 2022 aarch64 GNU/Linux
```

Can I do something to get it run?
Best

**Comment by aleksandr-kotlyar** [comment]
@ziza88 please format stacktrace with triple ` 
to separate stacktrace log rows like
```
one
two
etc.
```

**Comment by aleksandr-kotlyar** [comment]
@ziza88 ty

try to add to your code
```python 
from selenium.webdriver import ChromeOptions
options = ChromeOptions()
options.binary_location = "/path_to_binary/you_chromium_browser_on_rasp_pi"
```
final codeblock based on your example:
```python
from selenium.webdriver.chrome.service import Service as ChromiumService
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.utils import ChromeType
from selenium.webdriver import ChromeOptions

options = ChromeOptions()
options.binary_location = "/path_to_binary/you_chromium_browser_on_rasp_pi"

driver = webdriver.Chrome(
    service=ChromiumService(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()),
    options=options
)

driver.get('www.google.de')
```

**Comment by aleksandr-kotlyar** [comment]
@ziza88 how you doing? :)

Does chromium browser even work on rPi3?

Have some luck with it?

**Comment by aleksandr-kotlyar** [comment]
Same as https://github.com/SergeyPirogov/webdriver_manager/issues/482 and https://github.com/SergeyPirogov/webdriver_manager/issues/436
Answered in https://github.com/SergeyPirogov/webdriver_manager/issues/436#issuecomment-1427042421
