### ISSUE TITLE
Error while installing last selenium

### ISSUE THREAD

**Issue by andreileonsalas** [SergeyPirogov/webdriver_manager#435]
Hi, i tried to run the install step on github actions but got the following error

```
Run python scraper.py
Traceback (most recent call last):
  File "/home/runner/work/selenium-github-actions/selenium-github-actions/scraper.py", line [7](https://github.com/arkalseif/selenium-github-actions/runs/8262412671?check_suite_focus=true#step:7:8), in <module>
    chrome_service = Service(ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install())
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/webdriver_manager/core/download_manager.py", line 2[8](https://github.com/arkalseif/selenium-github-actions/runs/8262412671?check_suite_focus=true#step:7:9), in download_file
    response = self._http_client.get(url)
  File "/opt/hostedtoolcache/Python/3.[9](https://github.com/arkalseif/selenium-github-actions/runs/8262412671?check_suite_focus=true#step:7:10).13/x64/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 33, in get
    self.validate_response(resp)
  File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/[10](https://github.com/arkalseif/selenium-github-actions/runs/8262412671?check_suite_focus=true#step:7:11)5.0.5[17](https://github.com/arkalseif/selenium-github-actions/runs/8262412671?check_suite_focus=true#step:7:18)7/chromedriver_linux64.zip
Error: Process completed with exit code 1.
```

I used this simple repo to test

https://github.com/jsoma/selenium-github-actions

**Comment by osbm** [comment]
Yes i am getting this error too

**Comment by andreileonsalas** [comment]
> Yes i am getting this error too

somebody in the repo fixed it:

`- name: Remove default Chromium
   run: sudo apt purge chromium-browser
- name: Install a new Chromium
   run: sudo apt install -y chromium-browser`

they removed and reinstalled chromium.

More info: https://github.com/jsoma/selenium-github-actions/issues/4
