### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

### ISSUE THREAD

**Issue by steeljardas** [SergeyPirogov/webdriver_manager#447]
So my Selenium has been giving me PATH issues, and yes, I've went through every single StackExchange I could find to fix this issue. I 100% have the chromedriver.exe in the right place, I do have the PATH in system environment variables and yes, I can run chromedriver.exe by using that in CMD but somehow Python/Selenium still can't find the correct path despite me giving it directly.

Another solution people proposed was using webdriver_manager, so I try and I get this error no matter what browser I try to install:
`driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))`

Error:
```
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\webdriver_manager\core\driver.py", line 45, in get_version
    return self.get_latest_release_version()
  File "C:\Python\lib\site-packages\webdriver_manager\drivers\chrome.py", line 40, in get_latest_release_version
    browser_version = self.get_browser_version()
  File "C:\Python\lib\site-packages\webdriver_manager\core\driver.py", line 55, in get_browser_version
    return get_browser_version_from_os(self.get_browser_type())
  File "C:\Python\lib\site-packages\webdriver_manager\core\utils.py", line 141, in get_browser_version_from_os
    OSType.WIN: windows_browser_apps_to_cmd(
  File "C:\Python\lib\site-packages\webdriver_manager\core\utils.py", line 120, in windows_browser_apps_to_cmd
    powershell = determine_powershell()
  File "C:\Python\lib\site-packages\webdriver_manager\core\utils.py", line 272, in determine_powershell
    with subprocess.Popen(
  File "C:\Python\lib\subprocess.py", line 837, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python\lib\subprocess.py", line 1281, in _get_handles
    p2cread = msvcrt.get_osfhandle(self._get_devnull())
  File "C:\Python\lib\subprocess.py", line 1082, in _get_devnull
    self._devnull = os.open(os.devnull, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\SteelHard\Desktop\pthon\Article Generator\Article Bot\Botting Snippet PAA Short.py", line 282, in <lambda>
    Button(self.login_screen, text="Generate Articles", width=13, height=1, command=lambda:self.getArticle(self.text.get('1.0', 'end-1c').splitlines(),self.text2.get('1.0', 'end-1c').splitlines())).place(x=65,y=125, anchor=CENTER)
  File "C:\Users\SteelHard\Desktop\pthon\Article Generator\Article Bot\Botting Snippet PAA Short.py", line 405, in getArticle
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()),chrome_options = chrome_options,desired_capabilities=capabilities)
  File "C:\Python\lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Python\lib\site-packages\webdriver_manager\core\manager.py", line 26, in _get_driver_path
    binary_path = self.driver_cache.find_driver(driver)
  File "C:\Python\lib\site-packages\webdriver_manager\core\driver_cache.py", line 96, in find_driver
    driver_version = driver.get_version()
  File "C:\Python\lib\site-packages\webdriver_manager\core\driver.py", line 47, in get_version
    return self.get_browser_version()
  File "C:\Python\lib\site-packages\webdriver_manager\core\driver.py", line 55, in get_browser_version
    return get_browser_version_from_os(self.get_browser_type())
  File "C:\Python\lib\site-packages\webdriver_manager\core\utils.py", line 141, in get_browser_version_from_os
    OSType.WIN: windows_browser_apps_to_cmd(
  File "C:\Python\lib\site-packages\webdriver_manager\core\utils.py", line 120, in windows_browser_apps_to_cmd
    powershell = determine_powershell()
  File "C:\Python\lib\site-packages\webdriver_manager\core\utils.py", line 272, in determine_powershell
    with subprocess.Popen(
  File "C:\Python\lib\subprocess.py", line 837, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python\lib\subprocess.py", line 1281, in _get_handles
    p2cread = msvcrt.get_osfhandle(self._get_devnull())
  File "C:\Python\lib\subprocess.py", line 1082, in _get_devnull
    self._devnull = os.open(os.devnull, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: 'nul'
```

**Comment by aleksandr-kotlyar** [comment]
@steeljardas hi! Thats really wierd. I haven't met this on 7,8,8.1,10 windows versions when tested.

Please provide
- OS version
- python version
- wdm version
- log with enabled webdriver-manager logger

Also:
- have u cmd terminal or powershell installed on OS? what versions?

**Comment by aleksandr-kotlyar** [comment]
@steeljardas any updates? Can u provide more info requested above?
