### ISSUE TITLE
Webdriver not working on my ubuntu 22.04.1 LTS (Jammy Jellyfish)

### ISSUE THREAD

**Issue by gmouawad** [SergeyPirogov/webdriver_manager#461]
Hello I have ran the codes as mentioned in the code section for chrome and for firefox on selnium 4 and I am getting the below results:
1. For Chrome:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x564bf7208463 <unknown>
#1 0x564bf6fcc8d8 <unknown>
#2 0x564bf6ff4b6a <unknown>
#3 0x564bf6fefc05 <unknown>
#4 0x564bf7033802 <unknown>
#5 0x564bf70332af <unknown>
#6 0x564bf702b443 <unknown>
#7 0x564bf6ffc3c5 <unknown>
#8 0x564bf6ffd531 <unknown>
#9 0x564bf725adce <unknown>
#10 0x564bf725e192 <unknown>
#11 0x564bf723f93e <unknown>
#12 0x564bf725f103 <unknown>
#13 0x564bf7232d85 <unknown>
#14 0x564bf72800a8 <unknown>
#15 0x564bf7280239 <unknown>
#16 0x564bf729b492 <unknown>
#17 0x7f91c4796b43 <unknown>

2. For Firefox:
[WDM] - Downloading: 19.0kB [00:00, 7.46MB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 177, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

Your help is much appreciated, thanks

**Comment by jakemraz** [comment]
I also have a same issue with 'DevToolsActivePort' on Ubuntu 22.04.1.
In detail, I have successfully run it locally, but failed to run on the airflow web environment. (don't know why)
I tried to solve it with --headless, --no-sandbox and --disable-dev-shm-usage options, it works locally but still failed on airflow webserver.

**Comment by Hnitrogen** [comment]
Same problem either TAT

**Comment by aleksandr-kotlyar** [comment]
Not webdriver-manager issue. Ask selenium or ubuntu or firefox community.
