### ISSUE TITLE
Firefox is not working

### ISSUE THREAD

**Issue by dBerkeTurkmen** [SergeyPirogov/webdriver_manager#478]
### `My Code`
```python
def test():
    from selenium import webdriver
    from webdriver_manager.firefox import GeckoDriverManager
    from selenium.webdriver.firefox.service import Service as FirefoxService
    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))

test()
```
### `Versions`
```
selenium: 4.7.2
webdriver-manager: 3.8.5
python: 3.11.1
os: Windows 11 Pro Version 22H2 (OS Build 22621.1105)
```

### `My Console Log`
```python
[WDM] - Downloading: 19.0kB [00:00, 19.4MB/s]                   
Traceback (most recent call last):
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\geckotest.py", line 7, in <module>
    test()
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\geckotest.py", line 5, in test
    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\venv\Lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 197, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dBerk\My Drive\Dev\Python\PycharmProjects\Penguin\venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
```

<img src="https://i.imgur.com/MzyaUTS.png">

**Comment by aleksandr-kotlyar** [comment]
Invalid: selenium could not find binary.

Solution: Provide binary_location to firefox options into selenium webdriver.
