### ISSUE TITLE
Selenium webdriver_manager behind VPN using Python gives connection error

### ISSUE THREAD

**Issue by centhil** [SergeyPirogov/webdriver_manager#492]
I am using Selenium webdriver_manager behind VPN using Python gives and it gives me connection error. I have the proxy details, can you pls help to implement it?

I used the following python script ehich dowloads the driver and starts it:

from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

driver.get('https://pypi.org/project/webdriver-manager/')
driver.quit()
to install the driver binary automatically. But I get the below error:

File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\Lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed`

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 
703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 
386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 
1042, in _validate_conn
    conn.connect()
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000267F9B8EB80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed`

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, 
in send
    resp = conn.urlopen(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 
787, in urlopen
    retries = retries.increment(
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /110.0.5481/chromedriver_win32.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000267F9B8EB80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))`

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "C:\Users\XXXXXXX\eclipse-workspace\TestRobot\Samples\webdriver-managerTest.py", line 5, in <module>        
    driver = webdriver.Chrome(ChromeDriverManager().install())
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\core\manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\core\download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\webdriver_manager\core\http.py", 
line 32, in get
    resp = requests.get(url=url, verify=self._ssl_verify, stream=True, **kwargs)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 73, in get    return request("get", url, params=params, **kwargs)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, 
in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, 
in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\XXXXXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 565, 
in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443): Max retries exceeded with url: /110.0.5481/chromedriver_win32.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000267F9B8EB80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
Any solutions?

**Comment by lettow-humain** [comment]
This is the exact error message I was having [here](https://github.com/SergeyPirogov/webdriver_manager/issues/493#issuecomment-1469796547). This means WDM can't connect to `chromedriver.storage.googleapis.com` at all. Most likely this is because if you use a VPN not all traffic is being routed through it. Try to check your VPN adapter settings and make sure that all traffic is being routed through it.

**Comment by aleksandr-kotlyar** [comment]
@centhil hi! I think the reason was that you were offline and fallback was bit bugged.
https://github.com/SergeyPirogov/webdriver_manager/compare/v3.8.5...master#diff-6d080476e8425bb2e132a333539832fd307f777f71478299f4689d1655e3acfeL47

So you got double ConnectionError. First - latest release url, second - determined browser version with X.X.X pattern not available too - because you were offline + this url is invalid you were online.

Bug is fixed at master. Please try current master branch with fix and give your feedback. The release will come soon.
