### ISSUE TITLE
output a more helpful error message when offline

### ISSUE THREAD

**Issue by leggewie** [SergeyPirogov/webdriver_manager#493]
I ran into a problem with webdriver_manager.  The cause of the problem was that I was offline at the time.  The error message was giving no indication about this and could have been more helpful.

```
(alright) leggewie@work:~$ python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alright import WhatsApp
>>> messenger = WhatsApp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/alright/__init__.py", line 38, in __init__
    ChromeDriverManager().install(),
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/webdriver_manager/drivers/chrome.py", line 44, in get_url
    if version.parse(browser_version) < version.parse("106.0.5249.61") :
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/leggewie/bin/alright/lib/python3.10/site-packages/packaging/version.py", line 195, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
>>> 
```

**Comment by lettow-humain** [comment]
For me it puts out a quite verbose trace that clearly states:
```
urllib3.exceptions.MaxRetryError:
    HTTPSConnectionPool(host='chromedriver.storage.googleapis.com', port=443):
        Max retries exceeded with url:
            /111.0.5563/chromedriver_mac_arm64.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1036bf430>:
                Failed to establish a new connection:
                    [Errno 8] nodename nor servname provided, or not known'))
```
Are your packages up to date?

Anyway you can solve this by falling back to a local binary. Of course this only works, if you have had a working version running before.
```python
from requests import exceptions
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

try:
    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install())
    )
except exceptions.ConnectionError as e:
    wdmDriverPath = '~/.wdm/drivers/chromedriver/YOUR_PLATFORM/VERSION_NUMBER'
    driver = webdriver.Chrome(wdmDriverPath)
```
