### ISSUE TITLE
Firefox driver not importable from version 3.8.6 under Python 3.7 on Debian 10

### ISSUE THREAD

**Issue by maciejskorski** [SergeyPirogov/webdriver_manager#534]
Under this environment:
```console
(.venv) (base) maciej.skorski@kaggle-cpu-maciej:~/projects/brydz$ pip show selenium
Name: selenium
Version: 4.10.0
Summary: None
Home-page: https://www.selenium.dev
Author: None
Author-email: None
License: Apache 2.0
Location: /home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages
Requires: certifi, urllib3, trio, trio-websocket
Required-by: 
(.venv) (base) maciej.skorski@kaggle-cpu-maciej:~/projects/brydz$ pip show webdriver-manager
Name: webdriver-manager
Version: 3.8.6
Summary: Library provides the way to automatically manage drivers for different browsers
Home-page: https://github.com/SergeyPirogov/webdriver_manager
Author: Sergey Pirogov
Author-email: automationremarks@gmail.com
License: None
Location: /home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages
Requires: tqdm, requests, packaging, python-dotenv
Required-by: 
(.venv) (base) maciej.skorski@kaggle-cpu-maciej:~/projects/brydz$ python --version
Python 3.7.12
(.venv) (base) maciej.skorski@kaggle-cpu-maciej:~/projects/brydz$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
when running the minimal example from the [pypi docs](https://pypi.org/project/webdriver-manager/) for Firefox
```python
# selenium 4
from selenium import webdriver
from selenium.webdriver.firefox.service import Service as FirefoxService
from webdriver_manager.firefox import GeckoDriverManager

driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
```
I get the error
```console
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))
  File "/home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 68, in __init__
    super().__init__(command_executor=executor, options=self.options)
  File "/home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/maciej.skorski/projects/brydz/.venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

**Comment by SergeyPirogov** [comment]
It's not a WDM problem

**Comment by maciejskorski** [comment]
Thanks @SergeyPirogov your answer was very informative....

**Comment by SergeyPirogov** [comment]
Most probably you are running headed browser without a screen, try to use headless browser
