### ISSUE TITLE
cannot import name 'ChromeType' from 'webdriver_manager.core.utils' 

### ISSUE THREAD

**Issue by zipovuaapc** [SergeyPirogov/webdriver_manager#548]
Hello. From today I started to get such error on my CI jenkins job

--------
File "/usr/local/lib/python3.9/site-packages/helpers/drivers/selenium/fixtures/selenium_driver.py", line 9, in <module>
    from webdriver_manager.core.utils import ChromeType
ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/usr/local/lib/python3.9/site-packages/webdriver_manager/core/utils.py)
--------

I downgraded webdriver-manager and it works again

NOTE: I have selenium version 4.9.1

**Comment by vmred** [comment]
I also faced this error, downgraded to 3.9.0 and no such issue observed

**Comment by SergeyPirogov** [comment]
Provide exact versions. What is broken. If you import ChromeType somewhere is your code, them delete import and import again from right place

**Comment by vmred** [comment]
webdriver-manager == 3.9.1
selenium == 4.9.0

`Traceback (most recent call last):
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 774, in import_plugin
    __import__(importspec)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
    exec(co, module.__dict__)
  File "/Users/vmred/PycharmProjects/project/fixtures/navigation.py", line 3, in <module>
    from src.ui.actions.driver_actions import URLs
  File "/Users/vmred/PycharmProjects/project/src/ui/actions/driver_actions.py", line 6, in <module>
    from selene import be, have
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/__init__.py", line 218, in <module>
    from selene.support import shared as _shared  # noqa
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/support/shared/__init__.py", line 25, in <module>
    from selene.support.shared.browser import SharedBrowser
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/support/shared/browser.py", line 36, in <module>
    from selene.support.shared.config import SharedConfig
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/support/shared/config.py", line 40, in <module>
    from webdriver_manager.core.utils import ChromeType
ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/webdriver_manager/core/utils.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py", line 53, in <module>
    sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 147, in main
    config = _prepareconfig(args, plugins)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 328, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1067, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1354, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1256, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1133, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 556, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode, rootpath)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 573, in _try_load_conftest
    self._getconftestmodules(anchor, importmode, rootpath)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 602, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 650, in _importconftest
    self.consider_conftest(mod)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 732, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 488, in register
    ret: Optional[str] = super().register(plugin, name)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in register
    hook._maybe_apply_history(hookimpl)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 300, in _maybe_apply_history
    res = self._hookexec(self.name, [method], kwargs, False)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/Users/vmred/PycharmProjects/project/conftest.py", line 21, in pytest_addhooks
    pluginmanager.import_plugin('fixtures.navigation')
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 776, in import_plugin
    raise ImportError(
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 774, in import_plugin
    __import__(importspec)
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 172, in exec_module
    exec(co, module.__dict__)
  File "/Users/vmred/PycharmProjects/project/fixtures/navigation.py", line 3, in <module>
    from src.ui.actions.driver_actions import URLs
  File "/Users/vmred/PycharmProjects/project/src/ui/actions/driver_actions.py", line 6, in <module>
    from selene import be, have
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/__init__.py", line 218, in <module>
    from selene.support import shared as _shared  # noqa
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/support/shared/__init__.py", line 25, in <module>
    from selene.support.shared.browser import SharedBrowser
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/support/shared/browser.py", line 36, in <module>
    from selene.support.shared.config import SharedConfig
  File "/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/selene/support/shared/config.py", line 40, in <module>
    from webdriver_manager.core.utils import ChromeType
ImportError: Error importing plugin "fixtures.navigation": cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/Users/vmred/PycharmProjects/project/venv/lib/python3.10/site-packages/webdriver_manager/core/utils.py)
`
