### ISSUE TITLE
TypeError: expected string or bytes-like object, got 'NoneType'

### ISSUE THREAD

**Issue by roboes** [SergeyPirogov/webdriver_manager#553]
Hi,

I am using the latest versions of Google Chrome (115.0.5790.102), Selenium (4.10.0) and webdriver-manager (3.9.1).

When I try to run the following code on Python 3.11.4 on Windows:

```.py
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

chrome_options = webdriver.ChromeOptions()

webdriver.Chrome(
	service=Service(ChromeDriverManager().install()),
	options=chrome_options,
)
```

I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\webdriver_manager\core\manager.py", line 33, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 45, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\webdriver_manager\core\driver.py", line 51, in get_driver_version_to_download
    else self.get_latest_release_version()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\PYTHON~1\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 71, in get_latest_release_version
    if version.parse(determined_browser_version) >= version.parse("113"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\packaging\version.py", line 196, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

**Comment by SergeyPirogov** [comment]
Most probably wd manager can determine browser version from OS

**Comment by mskozlova** [comment]
This is actually fixed here: https://github.com/SergeyPirogov/webdriver_manager/pull/545

**Comment by roboes** [comment]
Thanks - the #545 fix does indeed solve this problem.

@SergeyPirogov Any idea when an updated version of webdriver-manager containing this fix will be available in pip?
