### ISSUE TITLE
having 502 within docker error even though proxy has been passed

### ISSUE THREAD

**Issue by b-guerra** [SergeyPirogov/webdriver_manager#555]
I  am having some serious issues trying to run selenium within a docker build.

I am currently hosting my application within Amazon ECS and building the docker using the following build command:

`docker build --progress=plain --build-arg http_proxy=MY_PROXY --build-arg https_proxy=MY_PROXY -f Dockerfile .
`

And everything executes fine until the selenium piece. It is giving me an error that comes back as a proxy error, you can see it below:

```
#16 [12/13] RUN python3.9 selenium_test.py
#16 sha256:1cd94ce583e70af04b8e24c32314a4586fa937a4d5a340d4be4614088ba4a668
#16 2.600 Traceback (most recent call last):
#16 2.600   File "/ricky/selenium_test.py", line 36, in <module>
#16 2.600     driver = webdriver.Chrome(
#16 2.600   File "/usr/local/lib/python3.9/dist-packages/seleniumwire/webdriver.py", line 218, in __init__
#16 2.600     super().__init__(*args, **kwargs)
#16 2.600   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 49, in __init__
#16 2.600     super().__init__(
#16 2.600   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chromium/webdriver.py", line 54, in __init__
#16 2.600     super().__init__(
#16 2.601   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
#16 2.601     self.start_session(capabilities)
#16 2.601   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 291, in start_session
#16 2.601     response = self.execute(Command.NEW_SESSION, caps)["value"]
#16 2.601   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
#16 2.601     self.error_handler.check_response(response)
#16 2.601   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 209, in check_response
#16 2.601     raise exception_class(value)
#16 2.601 selenium.common.exceptions.WebDriverException: Message: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
#16 2.601 <html>
#16 2.601 <!-- FileName: index.html
#16 2.601      Language: [en]
#16 2.601 -->
#16 2.601 <!--Head-->
#16 2.601 <head>
#16 2.601   <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
#16 2.601   <meta http-equiv="X-UA-Compatible" content="IE=7" />
#16 2.601   <title>McAfee Web Gateway - Notification</title>
#16 2.601   <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
#16 2.601   <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
#16 2.601 </head>
#16 2.601 <!--/Head-->
#16 2.601 <!--Body-->
#16 2.601 <body onload="swOnLoad();">
#16 2.601   <table class='bodyTable'>
#16 2.601     <tr>
#16 2.601       <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif'>
#16 2.601 <!--Logo-->
#16 2.601 <table class='logoTable'>
#16 2.601   <tr>
#16 2.601     <td class='logoData'>
#16 2.601       <a href='http://www.mcafee.com'>
#16 2.601         <img src='/mwg-internal/de5fs23hu73ds/files/default/img/logo_mwg.png'></a>
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601 </table>
#16 2.601 <!--/Logo-->
#16 2.601 <!--Contents-->
#16 2.601 <!-- FileName: cannotconnect.html
#16 2.601      Language: [en]
#16 2.601 -->
#16 2.601 <!--Title-->
#16 2.601 <table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
#16 2.601   <tr>
#16 2.601     <td class='titleData'>
#16 2.601       Cannot Connect
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601 </table>
#16 2.601 <!--/Title-->
#16 2.601
#16 2.601 <!--Content-->
#16 2.601 <table class="contentTable">
#16 2.601   <tr>
#16 2.601     <td class="contentData">
#16 2.601       The proxy could not connect to the destination in time.
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601 </table>
#16 2.601 <!--/Content-->
#16 2.601
#16 2.601 <!--Info-->
#16 2.601 <table class="infoTable">
#16 2.601   <tr>
#16 2.601     <td class="infoData">
#16 2.601       <b>URL: </b><script type="text/javascript">break_line("http://localhost:58957/session");</script><br />
#16 2.601       <p class="proxyErrorData">Failure Description: :cannotconnect:server state 1:state 9:Application response 502 cannotconnect</p>
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601 </table>
#16 2.601 <!--/Info-->
#16 2.601
#16 2.601 <!--/Contents-->
#16 2.601 <!--Policy-->
#16 2.601 <table class='policyTable'>
#16 2.601   <tr>
#16 2.601     <td class='policyHeading'>
#16 2.601       <hr>
#16 2.601       Company Acceptable Use Policy
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601   <tr>
#16 2.601     <td class='policyData'>
#16 2.601       This is an optional acceptable use disclaimer that appears on every page. You may change the wording or remove this section entirely in index.html.
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601 </table>
#16 2.601 <!--/Policy-->
#16 2.601 <!--Foot-->
#16 2.601 <table class='footTable'>
#16 2.601   <tr>
#16 2.601     <td class='helpDeskData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
#16 2.601       For assistance, please contact your system administrator.
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601   <tr>
#16 2.601     <td class='footData'>
#16 2.601       generated <span id="time">2023-07-21 13:28:22</span> by McAfee Web Gateway
#16 2.601       <br />
#16 2.601       selenium/4.10.0 (python linux)
#16 2.601     </td>
#16 2.601   </tr>
#16 2.601 </table>
#16 2.601 <!--/Foot-->
#16 2.601       </td>
#16 2.601     </tr>
#16 2.601   </table>
#16 2.601 </body>
#16 2.601 <!--/Body-->
#16 2.601 </html>
#16 2.601
#16 ERROR: executor failed running [/bin/sh -c python3.9 selenium_test.py]: exit code: 1
```

What makes me think it is not a proxy issue per se, is the fact that when trying to get the page HTML thru the requests package, it works fine.

You can see my selenium_test.py code below:
```

import logging
from seleniumwire import webdriver



selenium_logger = logging.getLogger('seleniumwire')
selenium_logger.setLevel(logging.DEBUG)


chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--disable-gpu')
chrome_options.add_argument('--headless=new')
chrome_options.add_argument("--ignore-certificate-errors")
chrome_options.add_argument("--disable-notifications")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument('--single-process')
chrome_options.add_argument('--no-zygote')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--remote-debugging-port=9222')
chrome_options.add_argument('--proxy-server=MY_PROXY')


sw_options = {
    'proxy': {
        'http': 'MY_PROXY',
        'https': 'MY_PROXY'
    },
    'ignore_http_methods': []
}


driver = webdriver.Chrome(
    options=chrome_options,
    seleniumwire_options=sw_options
)


driver.get("https://www.sec.gov/")
print(driver.title)

```

Honestly I have no idea of what is going on. If anyone could give me any light I would REALLY appreaciate, thank you very much.

I am using seleniumwire to handle the proxy connection, I tried using ChromeService to download the driver case it was the issue... Everything you can imagine, as I showed above.. nothing works...

I am sorry if this post should not be here, I really feeling without any other place to go

**Comment by SergeyPirogov** [comment]
It's an issue from selenium.
