### ISSUE TITLE
ChromeDriverManager().install() can't be called without version specified

### ISSUE THREAD

**Issue by cubicbyte** [SergeyPirogov/webdriver_manager#569]
Hi, when I use the README example for Chrome Selenium 4.x, I get the following error:

```
Traceback (most recent call last):
  File "D:\source\projects\reddit-account-generator\test.py", line 6, in <module>
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\webdriver_manager\chrome.py", line 39, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\webdriver_manager\core\manager.py", line 33, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url())
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 45, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\webdriver_manager\core\driver.py", line 51, in get_driver_version_to_download
    else self.get_latest_release_version()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 71, in get_latest_release_version
    if version.parse(determined_browser_version) >= version.parse("113"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\packaging\version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "D:\source\projects\reddit-account-generator\.venv\Lib\site-packages\packaging\version.py", line 196, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

This should work because driver_version has the following typing: Optional[str] = None

By the way, half of the examples in the README don't work, not just this one

## I use:
python 3.11.0
selenium 3.10.0
webdriver-manager==3.9.1

**Comment by SSAdvisor** [comment]
Lot's of recent issues with this problem. Thanks for trying the examples in the README. Hopefully this helps @SergeyPirogov to debug this issue.

**Comment by alfablac** [comment]
Is not this related to selenium v3?
I'm able to run that exact command, but my selenium version is 4.6, same wdm version.
(python is 3.9.6, just in case it's related to those common issues with python 3.10+)

**Comment by cubicbyte** [comment]
> Is not this related to selenium v3? I'm able to run that exact command, but my selenium version is 4.6, same wdm version. (python is 3.9.6, just in case it's related to those common issues with python 3.10+)

My bad, I specified the wrong version. Fixed it.

**Comment by alfablac** [comment]
@cubicbyte How is Google installed on you computer? Sounds like it's not in the usual folders, or you don't have powershell installed.
The cmd mapping wdm uses to check the version is
```
powershell -NoProfile "$ErrorActionPreference='silentlycontinue'; $tmp = (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKCU\SOFTWARE\Google\Chrome\BLBeacon").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome").version; if ($tmp) {echo $tmp; Exit;};"
```
Run this on cmd and see if you get your chrome version.
Most likely explains this error: TypeError: expected string or bytes-like object, got 'NoneType'

**Comment by cubicbyte** [comment]
> @cubicbyte How is Google Chrome installed on you computer? Sounds like it's not in the usual folders, or you don't have powershell installed. The cmd mapping wdm uses to check the version is
> 
> ```
> powershell -NoProfile "$ErrorActionPreference='silentlycontinue'; $tmp = (Get-Item -Path "$env:PROGRAMFILES\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:PROGRAMFILES (x86)\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-Item -Path "$env:LOCALAPPDATA\Google\Chrome\Application\chrome.exe").VersionInfo.FileVersion; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKCU\SOFTWARE\Google\Chrome\BLBeacon").version; if ($tmp) {echo $tmp; Exit;}; $tmp = (Get-ItemProperty -Path Registry::"HKLM\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Google Chrome").version; if ($tmp) {echo $tmp; Exit;};"
> ```
> 
> Run this on cmd and see if you get your chrome version. Most likely explains this error if you get an empty result: TypeError: expected string or bytes-like object, got 'NoneType'

Looks like you're right, after doing a little searching, I realized that I had a broken chrome installation. I reinstalled it and now the chrome version is detected.

But still I get an error that no driver for this version was found, and it looks like this problem has already been reported, so I think I'll close this issue.
