### ISSUE TITLE
The README example for Chrome doesn't work even with latest version

### ISSUE THREAD

**Issue by dariopnc** [SergeyPirogov/webdriver_manager#587]
After the Chrome Driver changes, my code stopped working, I then upgraded webdriver-manager but got another error.

I was able to reproduce it with the code example posted on the [README ](https://github.com/SergeyPirogov/webdriver_manager/blob/master/README.md) page.

```
Traceback (most recent call last):
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\MASKED_PATH_TO_PYTHON\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\MASKED_PATH_TO_PYTHON\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\MASKED_PATH_TO_PYTHON\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/known-good-versions-with-downloads.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\webdriver_manager\core\http.py", line 32, in get
    resp = requests.get(
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='googlechromelabs.github.io', port=443): Max retries exceeded with url: /chrome-for-testing/known-good-versions-with-downloads.json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MASKED_PATH_TO_CODE\test WDM.py", line 6, in <module>
    driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\webdriver_manager\drivers\chrome.py", line 44, in get_driver_download_url
    modern_version_url = self.get_url_for_version_and_platform(driver_version_to_download, os_type)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\webdriver_manager\drivers\chrome.py", line 69, in get_url_for_version_and_platform
    response = self._http_client.get(url)
  File "C:\MASKED_PATH_TO_VENV\lib\site-packages\webdriver_manager\core\http.py", line 35, in get
    raise exceptions.ConnectionError(f"Could not reach host. Are you offline?")
requests.exceptions.ConnectionError: Could not reach host. Are you offline?
```

Here's the requirements.txt file to generate the VENV I used to reproduce this case
```
selenium==4.4.3
webdriver-manager==4.0.0
```

**Comment by JaimeRB** [comment]
It seems to be related with the certificate issuer entity. Maybe a temporal connection error?

I got it working here on Pyhton 3.10.6

**Comment by dariopnc** [comment]
I might add that the VENV was based on python 3.9

**Comment by SergeyPirogov** [comment]
Not a WD issue
