### ISSUE TITLE
Doesn't seem to work when compiled with pyinstaller.

### ISSUE THREAD

**Issue by SaxonRah** [SergeyPirogov/webdriver_manager#62]
**[Problem]**
webdriver_manager is not downloading the correct driver due to config problems after it has been compiled down from pyinstaller.

Runs fine with Python 3.7 when running normally. After compiling with Pyinstaller, the result is the output is complaining about the config file missing values.
**[TEST CODE]**
```
from selenium.webdriver import Chrome
from webdriver_manager.chrome import ChromeDriverManager

browser = Chrome(executable_path=ChromeDriverManager().install())
```
**[Results - Running from python]**
```
Checking for win32 chromedriver:2.46 in cache
There is no cached driver. Downloading new one...
Trying to download new driver from http://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip
Unpack archive C:\Users\LordRah\.wdm\chromedriver\2.46\win32\chromedriver.zip

Process finished with exit code 0
```
Working as intended.

Now lets compile this down with pyinstaller and run it.

**[Results - Running from compiled exe - pyinstaller]**
**WITHOUT CONFIG INFO**
```
Traceback (most recent call last):
  File "src\test.py", line 4, in <module>
  File "site-packages\webdriver_manager\chrome.py", line 15, in __init__
  File "site-packages\webdriver_manager\driver.py", line 45, in __init__
  File "site-packages\webdriver_manager\driver.py", line 18, in __init__
  File "site-packages\webdriver_manager\config.py", line 28, in __getattr__
  File "site-packages\webdriver_manager\config.py", line 21, in get
  File "configparser.py", line 780, in get
  File "configparser.py", line 1146, in _unify_values
configparser.NoSectionError: No section: 'ChromeDriver'
[9700] Failed to execute script test
```

**[Quick-Fix Solution]**
Ooops looks like we need the config.ini file created in the .wdm folder.
Add some info about what driver to download in the ini file and it will then work.
```
[ChromeDriver]
version = latest
name = chromedriver
driver_path = C:/Users/Admin/.wdm/chromedriver
url = https://chromedriver.storage.googleapis.com
offline = False
driver_latest_release_url = https://chromedriver.storage.googleapis.com/LATEST_RELEASE
```

**[Results - Running from compiled exe - pyinstaller]**
**WITH CONFIG INFO**
```
Checking for win32 chromedriver:73.0.3683.68 in cache
There is no cached driver. Downloading new one...
Trying to download new driver from https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_win32.zip
Unpack archive C:\Users\LordRah\.wdm\chromedriver\73.0.3683.68\win32\chromedriver.zip

DevTools listening on ws://127.0.0.1:55067/devtools/browser/de0f5d8d-ca18-482e-9e0f-1973c7d8d4ec
```

I am not sure how to solve it really as i haven't looked much into the problem, but it could be some permissions issue. In any case i hope this can be fixed soon!

**Comment by DanielGnzlzVll** [comment]
Hi SaxonRah,
I had the same problem, and I solved it by adding the flag `` --add-data``

```bash
pyinstaller mymodule/entrypoint.py --add-data "env\lib\site-packages\webdriver_manager\default.ini;webdriver_manager"
```
