### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by StefanoGiu** [SergeyPirogov/webdriver_manager#623]
I have installed webdriver_manager 4.0.0 on Windows 10 with Python 3.11
If I try to execute:
webdriver.Chrome(service=Service(ChromeDriverManager().install())

I got the following error:
Traceback (most recent call last):
  File "Test.py", line 50, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=woptions)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\site-packages\webdriver_manager\core\manager.py", line 35, in _get_driver_binary_path
    binary_path = self._cache_manager.find_driver(driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\site-packages\webdriver_manager\core\driver_cache.py", line 106, in find_driver
    metadata = self.load_metadata_content()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\site-packages\webdriver_manager\core\driver_cache.py", line 135, in load_metadata_content
    return json.load(outfile)
           ^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "XXX\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kris-dev-cloudwarelab** [comment]
Im getting the same issue on one of our devices, totally unclear why

**Comment by SergeyPirogov** [comment]
delete .wdm folder and try again
