### ISSUE TITLE
pydriod3 cannot run！！！

### ISSUE THREAD

**Issue by liuxb99** [SergeyPirogov/webdriver_manager#640]
# selenium 4
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))

《error occur》

/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-stable: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-beta: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-dev: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-stable: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-beta: not found
/data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-dev: not found
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 6, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/webdriver_manager/chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/webdriver_manager/core/manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/webdriver_manager/drivers/chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/webdriver_manager/core/driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.9/site-packages/webdriver_manager/drivers/chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
AttributeError: 'NoneType' object has no attribute 'split'

[Program finished]

**Comment by proDreams** [comment]
Same problem on Windows 11 and Python 3.11

```
C:\python311\python.exe D:\metal-calculator\test.py 
"powershell" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
"powershell" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
Traceback (most recent call last):
  File "D:\metal-calculator\test.py", line 10, in <module>
    driver_path = ChromeDriverManager().install()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\webdriver_manager\chrome.py", line 40, in install
    driver_path = self._get_driver_binary_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\webdriver_manager\core\manager.py", line 40, in _get_driver_binary_path
    file = self._download_manager.download_file(driver.get_driver_download_url(os_type))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 32, in get_driver_download_url
    driver_version_to_download = self.get_driver_version_to_download()
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\webdriver_manager\core\driver.py", line 48, in get_driver_version_to_download
    return self.get_latest_release_version()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\python311\Lib\site-packages\webdriver_manager\drivers\chrome.py", line 64, in get_latest_release_version
    determined_browser_version = ".".join(determined_browser_version.split(".")[:3])
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

Process finished with exit code 1
```

**Comment by maxi07** [comment]
same error here :(

**Comment by AvianJay** [comment]
> /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-stable: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-beta: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-dev: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-stable: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-beta: not found /data/user/0/ru.iiec.pydroid3/files/sh: google-chrome-dev: not found

Because it does not support android, unless you install the linux version of chrome-stable in android

**Comment by aleksandr-kotlyar** [comment]
Thanks for reporting this.

This is primarily an environment/scope issue: PyDroid/Android does not provide a desktop Chrome runtime expected by webdriver-manager + desktop ChromeDriver flows.

I added a docs clarification about supported scope and guidance to use Appium (UiAutomator2) for Android Chrome/WebView automation.

So this is not a webdriver-manager core runtime bug; it is an unsupported environment for this usage pattern.
