### ISSUE TITLE
Chrome beta version

### ISSUE THREAD

**Issue by Smawexi** [SergeyPirogov/webdriver_manager#641]
Can we implement a driver that can download Chrome test versions,
For example, a class can be provided to download a zip file with a specified URL. The URL for the Chrome test version is different from the official version, and using the current implementation to download the driver for the Chrome test version can be cumbersome
-------------------------------------------------------------------------------------------------
This is because I am using a beta version of Chrome in Windows, which resulted in an error:
Traceback (most recent call last):
File "D:  Test  Python Test  tests  demo. py", line 5, in<module>
Driver=webdriver Chrome (ChromeDriverManager(). install())
File "D:  fsy  Anaconda3  lib  site packages  webdriver_manager  chrome. py", line 39, in install
Driver_ Path=self_ Get_ Driver_ Path (self. driver)
File "D:  fsy  Anaconda3  lib  site packages  webdriver_manager  core  manager. py", line 30, in_ Get_ Driver_ Path
File=self_ Download_ Manager. download_ File (driver. get_url())
File "D:  fsy  Anaconda3  lib  site packages  webdriver_manager  core  download_manager. py", line 28, in download_ File
Response=self_ HTTP_ Client. get (URL)
File "D:  fsy  Anaconda3  lib  site packages  webdriverManager  core  http. py", line 33, in get
Self. validate_ Response (resp)
File "D:  fsy  Anaconda3  lib  site packages  webdriverManager  core  http. py", line 16, in validate_ Response
Raise ValueError (f "There is no such driver by url {resp. url}")
ValueError: There is no such driver by URL https://chromedriver.storage.googleapis.com/117.0.5938/chromedriver_win32.zip

**Comment by Smawexi** [comment]
For people who are not familiar with this package (have not seen the source code), trying to implement a custom implementation will be very unfamiliar and may cause a series of problems. It would be great if the developers could provide some simple and easy-to-use implementations. For example, add a chrome driver for downloading a custom URL. After briefly looking at the source code, the current implementation only downloads the URL for the official version of chrome...

**Comment by ndepaola** [comment]
does this meet your needs? https://www.selenium.dev/documentation/selenium_manager/#automated-browser-management
