### ISSUE TITLE
WebDriverException: Service chromedriver unexpectedly exited. Status code was: -5

### ISSUE THREAD

**Issue by ylhan** [SergeyPirogov/webdriver_manager#677]
I'm trying to run chrome within AWS MWAA but the webdriver exits each time with status code -5.

Grab the image from https://github.com/aws/aws-mwaa-local-runner and run it

Once the container is running you can bash into it, install selenium and the webdriver-manager and run the following script.
```python
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromiumService
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.core.os_manager import ChromeType
from selenium.webdriver.chrome.options import Options
options = Options()
options.add_argument("--headless=new")
driver = webdriver.Chrome(
    service=ChromiumService(
        ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()
    ),
    options=options,
)
```

Error log
```
>>> options = Options()
>>> options.add_argument("--headless=new")
>>> driver = webdriver.Chrome(
...             service=ChromiumService(
...                 ChromeDriverManager(chrome_type=ChromeType.CHROMIUM).install()
...             ),
...             options=options,
...         )

DEBUG:selenium.webdriver.common.driver_finder:Skipping Selenium Manager; path to chrome driver specified in Service class: /usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver
DEBUG:selenium.webdriver.common.service:Started executable: `/usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver` in a child process with pid: 19414 using 0 to output -3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 102, in start
    self.assert_process_still_running()
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 115, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /usr/local/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: -5

>>> 
>>> 
```

**Comment by sevroauasmo** [comment]
same error, code is -9

**Comment by saattrupdan** [comment]
Having the same issue, just with Chrome instead of Chromium.

**Comment by aleenprd** [comment]
Same issue. Works locally but fails in a containerized environment.

**Comment by aleksandr-kotlyar** [comment]
Thanks for the report.

Yes, this class of issue is addressed in newer code, but it is reproducible with older versions (including `webdriver-manager==4.0.2`), where Chromium/Chrome driver resolution could fall back to an old `114` driver.

Relevant fixes:
- `1c59212` (2024-12-18, `#685`): switched Chrome/Chromium driver resolution to Chrome for Testing endpoints.
- `a2f60b4` (2026-05-17, `#715`): fixed browser version detection path used during resolution.
- `727c4b9` (2026-05-17, `#706`): added fallback when exact CfT build metadata is missing.

Recommended actions:
1. Upgrade `webdriver-manager` to a newer release (preferably latest).
2. Clear old `.wdm` cache so stale `114` binaries are not reused.
3. Keep `chrome_type=ChromeType.CHROMIUM` for MWAA/Chromium.
4. Use stable container flags: `--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu`.
5. If it still fails with status `-5`, attach full `chromedriver` verbose logs — at that point it is often a Chromium runtime/container crash, not a driver-resolution bug.
