### ISSUE TITLE
Unable to setup: Critical :This version of ChromeDriver only supports Chrome version 114 Current browser version is 131.0.6778.70

### ISSUE THREAD

**Issue by laxmithurv** [SergeyPirogov/webdriver_manager#687]
Webdriver is pointed to cache version of 114 chromedriver version, and not picking up the current browser version 131. 
It works for firefox and not for Chrome. Below is the error

selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 

Python version - Python 3.10.2

Selenium Version - 4.22.0

Webdriver-manager
 version -4.0.2

Please help me in this regard, as I'm getting driver mismatch error for past 1 month and unable to fix

Code
$ ./run-ui-code.sh
Running test case: XXXXXXXX
[INFO] 2024-11-18 20:58:58,031 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Starting web interface at http://localhost:8089/ (accepting connections from all network interfaces)
[INFO] 2024-11-18 20:58:58,047 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Starting Locust 2.31.5
[INFO] 2024-11-18 20:58:58,047 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: No run time limit set, use CTRL+C to interrupt
[INFO] 2024-11-18 20:58:58,084 LAPTOP-7RK7NGFK/locust.runners [thread: Thread-1]: Ramping to 1 users at a rate of 1.00 per second
[INFO] 2024-11-18 20:58:58,100 LAPTOP-7RK7NGFK/locust.runners [thread: Thread-1]: All users spawned: {"WebUser": 1} (1 total users)
[INFO] 2024-11-18 20:58:58,100 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: For Test Run -> User Role: "Customer : Administrator"
[INFO] 2024-11-18 20:58:58,100 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Getting User Data Of Account Type: "Customer" with Role: "Administrator" with Account: "None"
[INFO] 2024-11-18 20:58:58,116 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Service Detail for the test run is:
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[INFO] 2024-11-18 20:58:58,116 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Step started: User_Launch_And_Login_Bridge_Marketplace_And_Switch_Account
[INFO] 2024-11-18 20:58:58,116 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: ====== WebDriver manager ======
[INFO] 2024-11-18 20:59:02,390 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-18 20:59:02,644 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip
[INFO] 2024-11-18 20:59:02,791 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Driver downloading response is 200
[INFO] 2024-11-18 20:59:05,902 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-18 20:59:08,286 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Get LATEST chromedriver version for google-chrome
[INFO] 2024-11-18 20:59:10,414 LAPTOP-7RK7NGFK/WDM [thread: UserThread-2]: Driver has been saved in cache [C:\Users\LaxmiTG.wdm\drivers\chromedriver\win64\114.0.5735.90]

DevTools listening on ws://127.0.0.1:61883/devtools/browser/2ebd28e8-31e9-48ee-ae54-c4e8d530889d
[ERROR] 2024-11-18 20:59:19,517 LAPTOP-7RK7NGFK/root [thread: UserThread-2]: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
GetHandleVerifier [0x008DA813+48355]
(No symbol) [0x0086C4B1]
(No symbol) [0x00775358]
(No symbol) [0x007961AC]
(No symbol) [0x00791EF3]
(No symbol) [0x00790579]
(No symbol) [0x007C0C55]
(No symbol) [0x007C093C]
(No symbol) [0x007BA536]
(No symbol) [0x007982DC]
(No symbol) [0x007993DD]
GetHandleVerifier [0x00B3AABD+2539405]
GetHandleVerifier [0x00B7A78F+2800735]
GetHandleVerifier [0x00B7456C+2775612]
GetHandleVerifier [0x009651E0+616112]
(No symbol) [0x00875F8C]
(No symbol) [0x00872328]
(No symbol) [0x0087240B]
(No symbol) [0x00864FF7]
BaseThreadInitThunk [0x7569FCC9+25]
RtlGetAppContainerNamedObjectPath [0x7720809E+286]
RtlGetAppContainerNamedObjectPath [0x7720806E+238]
Traceback (most recent call last):
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\ctf\helpers\taskset_handler.py", line 185, in decorator
res = fnc(*args, **kwargs)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\locust\user\task.py", line 385, in execute_task
task(self)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\helpers\kb_helper.py", line 40, in log_step
func(self, *args, **kwargs)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\tests\kb\taskset_common.py", line 40, in user_launch_and_login_bridge_marketplace_and_switch_account
self.client.set_driver(proxy=self.proxy)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\ctf\lib\selenium_locust\core.py", line 140, in set_driver
self.driver = ChromeDriver(
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\ctf\lib\webdrivers\drivers.py", line 113, in new
driver = webdriver.Chrome(service=ChromeService(DriverBinarySingleton.binary_path), options=options)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in init
super().init(
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in init
super().init(command_executor=executor, options=options)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in init
self.start_session(capabilities)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
response = self.execute(Command.NEW_SESSION, caps)["value"]
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
self.error_handler.check_response(response)
File "C:\Users\LaxmiTG\Downloads\Workspace\ui_code\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 131.0.6778.70 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
GetHandleVerifier [0x008DA813+48355]
(No symbol) [0x0086C4B1]
(No symbol) [0x00775358]
(No symbol) [0x007961AC]
(No symbol) [0x00791EF3]
(No symbol) [0x00790579]
(No symbol) [0x007C0C55]
(No symbol) [0x007C093C]
(No symbol) [0x007BA536]
(No symbol) [0x007982DC]
(No symbol) [0x007993DD]
GetHandleVerifier [0x00B3AABD+2539405]
GetHandleVerifier [0x00B7A78F+2800735]
GetHandleVerifier [0x00B7456C+2775612]
GetHandleVerifier [0x009651E0+616112]
(No symbol) [0x00875F8C]
(No symbol) [0x00872328]
(No symbol) [0x0087240B]
(No symbol) [0x00864FF7]
BaseThreadInitThunk [0x7569FCC9+25]
RtlGetAppContainerNamedObjectPath [0x7720809E+286]
RtlGetAppContainerNamedObjectPath [0x7720806E+238]

[INFO] 2024-11-18 20:59:19,663 LAPTOP-7RK7NGFK/root [thread: Thread-4]: Iteration limit reached (1), stopping test
[INFO] 2024-11-18 20:59:28,877 LAPTOP-7RK7NGFK/root [thread: Thread-4]: --autoquit time reached, shutting down
[INFO] 2024-11-18 20:59:28,946 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: writing html report to file: .\kb-functional-test-report.html
[INFO] 2024-11-18 20:59:28,946 LAPTOP-7RK7NGFK/locust.main [thread: MainThread]: Shutting down (exit code 1)

**Comment by laxmithurv** [comment]
Any update?

**Comment by laxmithurv** [comment]
Any update @SergeyPirogov ? Still facing the issue

**Comment by Ronkiro** [comment]
any update?

**Comment by Ronkiro** [comment]
For future seekers, using Selenium Manager apparently solved my case (https://www.selenium.dev/documentation/selenium_manager/)

It's as simple as declaring no `Service`

```py
webdriver.Chrome(options=chrome_options)
```

**Comment by stephen-a2z** [comment]
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 112.0.5615.49 with binary path /usr/bin/chromium-browser
I encountered the same issue

**Comment by misterhell** [comment]
Hey guys, look what I've recently found
Url that is used in **latest_release_url** from ChromeDriverManager constructor, return not really latest version, when i'm writing it it returns 114.0.5735.90
```python
class ChromeDriverManager(DriverManager):
  def __init__(
            self,
            driver_version: Optional[str] = None,
            name: str = "chromedriver",
            url: str = "https://chromedriver.storage.googleapis.com",
            latest_release_url: str = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE",
            chrome_type: str = ChromeType.GOOGLE,
            download_manager: Optional[DownloadManager] = None,
            cache_manager: Optional[DriverCacheManager] = None,
            os_system_manager: Optional[OperationSystemManager] = None
    ):
```
### Solution
Replace it for https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE, which returns actual version

```python
service = ChromeService(ChromeDriverManager(latest_release_url="https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE").install())
driver = webdriver.Chrome(service=service, options=options)
```

**Comment by aleksandr-kotlyar** [comment]
This is fixed in the current codebase, but **not in `webdriver-manager==4.0.2`**.

Relevant fixes:
- `1c59212` (2024-12-18, `#685`): switched Chrome driver source to Chrome for Testing endpoints.
- `a2f60b4` (2026-05-17, `#715`): fixed browser version detection bug in OS manager that could cause fallback to older driver resolution.
- `727c4b9` (2026-05-17, `#706`): added robust fallback when exact CfT build metadata is missing.
